### ISSUE TITLE
Two mini hubs

### ISSUE THREAD

**Issue by morgsman** [OpenWonderLabs/SwitchBotAPI#100]
### Current Situation

If I purchase an extra hub and attach devices to it will I be able to control all my devices via the api? Some will be connected to one hub and others to the second hub. I assume yes as they would all use the same token attached to the account but has anyone been able to do this? Thx. 

### Logs

```markdown
X
```

### Configuration

```json
X
```

### Environment

 - OS:
- Software:
- Node:
- npm:

**Comment by AdyRock** [comment]
Yes. Both hubs will receive the commands and forward them on via BLE to the devices that are in range.
Basically you are not adding devices to a hub as such but to your account. You can therefore have multiple hubs to cover a larger area and you don't have to worry about it.

**Comment by morgsman** [comment]
Thanks for the clarification. Just what I needed.
