### ISSUE TITLE
Control Smart Lock without using SwitchBot App

### ISSUE THREAD

**Issue by MinhTuan172** [OpenWonderLabs/SwitchBotAPI#101]
### Current Situation

Hi, 
Is there a way to lock/unlock Smart Lock without using SwitchBot App ?
Thank you in advance!

### Logs

```markdown
X
```

### Configuration

```json
X
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Additional Context

no response

**Comment by MinhTuan172** [comment]
any update ?

**Comment by MinhTuan172** [comment]
any update ?

**Comment by DucHVD** [comment]
any update?

**Comment by DucHVD** [comment]
Do you plan to update?
