### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by tecnolive** [OpenWonderLabs/SwitchBotAPI#104]
### Current Situation

Hi, 

has anyone developed a plugin to integrate switchbot hub mini (IR) into home assistant?
How can I check the air conditioner with the home assistant?

### Proposed Change

Develop integration home assistant

**Comment by labaland** [comment]
Please add integration :(

**Comment by lukes-ha** [comment]
+

**Comment by lukes-ha** [comment]
yes, that would be perfect. I don't understand why the plug in isn't supporting the hub.
