### ISSUE TITLE
Control Smart Lock without using SwitchBot App

### ISSUE THREAD

**Issue by DucHVD** [OpenWonderLabs/SwitchBotAPI#105]
### Current Situation

Hi,

 
My first SwitchBot Lock has arrived, and I want to connect with SwitchBot Lock without using SwitchBot App.
Is there a way to lock/unlock Smart Lock without using SwitchBot App ? Could you please direct me to the API reference manual?
 

Regards,

Duc.

### Logs

```markdown
don't have
```

### Configuration

```json
don't have
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by DucHVD** [comment]
do you have?

**Comment by AdyRock** [comment]
The API reference manual is under the code section on here.
But, you will need to add the lock to your SwitchBot account via the phone app before you can control it using the API.
You will also need a SwitchBot hub so your account on the server can send commands to the Lock.

I'm not aware of any BLE or WiFi documentation to control the lock directly from anything, so maybe someone can correct me on that?

**Comment by DucHVD** [comment]
@AdyRock
 thank you so much!

**Comment by DucHVD** [comment]
any update?

**Comment by DucHVD** [comment]
Do you plan to update?

**Comment by donavanbecker** [comment]
You can control it. They just haven't published it. Look at homebridge plugin, beta branch.

**Comment by DucHVD** [comment]
@donavanbecker thank you! I am very happy to receive your reply.
Also do you know when SwitchBot will release API/SDK of SwitchBot Lock?
And do you know someone who knows this well so I can contact them directly?

**Comment by donavanbecker** [comment]
@DucHVD I do not. We will have to wait for someone from SwitchBot to add it to the documentation.

**Comment by Tom-Todd** [comment]
@DucHVD I worked out the commands to unlock / lock it remotely by using postman, it's possible there are further commands there that I haven't found yet. Might be worth playing around with if you've got time.
