### ISSUE TITLE
If switchbot hub mini lost connect to wifi, when i call api to control other devices through switchbot hub mini, what return?

### ISSUE THREAD

**Issue by trungnguyengk** [OpenWonderLabs/SwitchBotAPI#106]
### Current Situation

Hi,
I am Trung, I am a developer. Currently I am developing an application that controls devices through a mini switch bot hub (specifically through the API you provided). In the case that my home wifi is faulty, but the switchbot hub mini connects to it. So in this case, I call the API to control the device through the switchbot hub mini, how will it return?

### Logs

```markdown
No
```

### Configuration

```json
No
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by vimalbhaya** [comment]
As per the documentation, the response.json()['statusCode'] will show 171 or 161 as code if the hub is offline. I'll let the Switchbot team chime in as well.

You can experiment the POST's reply by actually turning the hub off in your setup or disconnect the fiber/modem to your Wifi AP to simulate a bad Wifi event. I guess both will act similar.
