### ISSUE TITLE
Faulty temperature data in API

### ISSUE THREAD

**Issue by vimalbhaya** [OpenWonderLabs/SwitchBotAPI#107]
### Analysis

Hi,

In my setup, there are multiple Hubs and multiple sensors in a single room. Multiple hubs are needed to get a 1-to-1 control of each IR device since remote codes for two devices are same. I shield the IR of each hub enough such that one hub doesn't control other devices its not meant to control and vice versa.

**Problem:** The temperature sensor read through API get stuck at same value. I'm not sure if the Switchbot app was also showing the same temperature, though I guess so since the app must be using same API internally.

**_Also, the internal CSV export (through mobile app) with 1 minute granularity doesn't have stuck values and they change so this looks like a communication issue._**

**Analysis**: If all hubs of that area are switched off, the API still returns value of the temperature sensor. Ideally, should get hub offline error in the GET, though there is no 171 or 161 error code defined for GETs.

**Method to Replicate**: Keep all hubs offline. The API still returns temperature sensor value (last known value) and remains stuck at that.

**Questions for switchbot team** : 
1. One of the hubs in our setup does gets offline once in a while. Is this causing it? I'm guessing so since sensors must be choosing a particular hub to transmit data and power OFF/ON of one hub might be causing it. Please note that there are 2-3 hubs ALWAYS ON and in range so the temperature sensor should be reachable through one of them.
2. What is the architecture of meter reads if there are multiple hubs in the same environment? 
3. What happens if one of the hubs goes offline . Does the BLE network self-heal such that temperature meter automatically gets synced through another hub which is still online and in range?

### Expected Behavior

The temperature data logged internally doesn't match what I get from API request at same time. I have taken care of time zone conversion.

### Steps To Reproduce

Keep all hubs offline. The API still returns temperature sensor value (last known value) and remains stuck at that.

### Logs

```markdown
Already explained the issue enough
```

### Configuration

```json
3 hubs in same area of approx 1100 sq-ft. All temperature sensors should be reachable by all hubs since they are mostly in line of sight and within 10-15 meters while switchbot advertised range is 120m.
```

### Environment

Mac and Linux. Shouldn't matter as such, IMO.

### Additional Context

**Questions for switchbot team** : 
1. One of the hubs in our setup does gets offline once in a while. Is this causing it? I'm guessing so since sensors must be choosing a particular hub to transmit data and power OFF/ON of one hub might be causing it. Please note that there are 2-3 hubs ALWAYS ON and in range so the temperature sensor should be reachable through one of them.
2. What is the architecture of meter reads if there are multiple hubs in the same environment? 
3. What happens if one of the hubs goes offline . Does the BLE network self-heal such that temperature meter automatically gets synced through another hub which is still online and in range?

**Comment by vimalbhaya** [comment]
I've checked with an offline hub. Same issue - API returns status code 100 and gives the last known temperature. Ideally, should give 171/161 (not defined in GETs ) or at least something other than 100 to signify success.

However, in the app, for an offline hub, it doesn't show the temperature which means that the app is somehow able to figure out offline hub. I have ways to figure that out at my end as well but still not a good solution. The meter reads should note it in status.

**Comment by vimalbhaya** [comment]
It is still happening. If I open the app, the API comes to senses and starts giving correct values. What might be causing it?

**Comment by AdyRock** [comment]
The sensors are constantly broadcasting the data via BLE, so all the hubs that are within range should receive the updates. I believe the hubs communicate with the server via MQTT and will send a new value when it detects a change (e.g. it receives a new value from the broadcast). When you open the phone app, it too receives updates via the BLE broadcasts, so it is not using the same API as your app.
The API will report the last value that was sent to the server.
The first thing I would suggest is you ensure the sensor is within BLE range of the hub so you know it can receive the broadcasts.
