### ISSUE TITLE
why not have field battery in api as: get all devices/ get status device?

### ISSUE THREAD

**Issue by trungnguyengk** [OpenWonderLabs/SwitchBotAPI#111]
### Current Situation

I am Trung, I am a developer. Currently I am developing an application that controls devices through a mini switch bot hub (specifically through the API you provided). I need know battery of device to me can replace or announce to client. You can provide add 1 feild battery for me?

### Logs

```markdown
No
```

### Configuration

```json
No
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by ganlbarone** [comment]
This has been a request for nearly 2 years now. They dont make improvements to the API.

**Comment by trungnguyengk** [comment]
hey, are you here to answer and impove your api?

**Comment by trungnguyengk** [comment]
Hello, how are you? Currently, I am developing manage all device connect to switchbot hub mini, but i dont see field battery when i call api get status, which can help me better. You had it? if not, you can made it in the future? If you have, you can provide for me?
