### ISSUE TITLE
How to get Motion detection history

### ISSUE THREAD

**Issue by kai0310** [OpenWonderLabs/SwitchBotAPI#114]
### Current Situation

I have purchased a motion sensor and SwitchBot Hub and am using the SwitchBot API.

I was able to get whether or not the SwitchBot was detecting motion when I hit the API, but I am unable to get when in the past the SwitchBot has detected motion.

Also, SwitchBot only returns motion detection every minute, but I would like to get real-time motion detection history. Is there any way to do this?

### Logs

```json
{"statusCode":100,"body":{"deviceId":<DEVICE ID>,"deviceType":"Motion Sensor"},"message":"success"}
```

### Configuration

```
curl --request GET 'https://api.switch-bot.com/v1.0/devices/<DEVICE ID>/status' \
  --header 'Authorization: <token>' \
  --header 'Content-Type: application/json; charset=utf8'
```

### Environment

- OS: macOS Monterey 12.3

**Comment by donavanbecker** [comment]
Have you enabled cloud services?

**Comment by kai0310** [comment]
@donavanbecker 
Thanks. I was able to get this.

However, I did not get the response I expected. can I get a history of the motion detection that SwitchBot got? I would also like to get the detection as it is in the shortest time possible, not every minute, but as close to the raw data of the SwitchBot as possible.

**Comment by kai0310** [comment]
Changed the title and text to what I want to do
