### ISSUE TITLE
Have SDK connect and control switchbot lock through bluetooth on my app ( not switchbot app )

### ISSUE THREAD

**Issue by trungnguyengk** [OpenWonderLabs/SwitchBotAPI#116]
### Current Situation

I am Trung, I am a developer. Currently I am developing an application that controls devices through a switchbot hub mini in project smart hotel (specifically through the API you provided). Because my project need control devices switchbot so i need the SDK to connect and control swiitchbot lock. Do you already have SDK? If you have, can you provide it to me? If not, can you do SDK in upcoming releases?

### Logs

```markdown
No
```

### Configuration

```json
No
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by trungnguyengk** [comment]
Hello, you can consider it, please?

**Comment by Hoa-nth** [comment]
Can you help me answer this question?
