### ISSUE TITLE
Is there an api so other systems can connect to the key directly without going through the Switchbox App?

### ISSUE THREAD

**Issue by trungnguyengk** [OpenWonderLabs/SwitchBotAPI#117]
### Current Situation

I am Trung, I am a developer. Currently I am developing an application that controls devices through a switchbot hub mini in project smart hotel (specifically through the API you provided). Because my project need control devices switchbot so i need the apis are described below with pictures. Do you already have these APIs? If you have, can you provide it to me? If not, can you do these api in upcoming releases?
Thank you!
![origin_img_v2_dcccd176-ac64-42da-8eca-60756832a1bh](https://user-images.githubusercontent.com/105915994/179169642-3297deff-b99a-437e-91b9-a297d6548d26.jpg)
![origin_img_v2_4add0733-bb66-4afb-a572-fe6486b9a7ah](https://user-images.githubusercontent.com/105915994/179169679-ccd042c4-12cf-47bd-925f-3d2a0bbc4b12.jpg)

### Logs

```markdown
No
```

### Configuration

```json
No
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by trungnguyengk** [comment]
Hello, you can consider with this question?

**Comment by Hoa-nth** [comment]
Hello, you can consider with this question?

**Comment by Hoa-nth** [comment]
We only need Api No.4, does the Switchbox side provide it?
