### ISSUE TITLE
Retrieving Meter history through API

### ISSUE THREAD

**Issue by lhegstrom** [OpenWonderLabs/SwitchBotAPI#118]
### Current Situation

When using the switchbot iPhone app - one can see a chart of the historical temperature and humidity from a meter. When using the API, and making a call to find the status of a device, I get back the appropriate response:

```
{'statusCode': 100,
 'body': {'deviceId': '############',
  'deviceType': 'Meter',
  'hubDeviceId': '##########',
  'humidity': 80,
  'temperature': 23.7},
 'message': 'success'}
```

### Proposed Change

Is it possible to expose whatever the iPhone app is using to the API?

Something along the lines of:

`GET /v1.0/devices/{METER_ID}/history`

Which returns the measurements stored on the meter?

**Comment by oliviertassinari** [comment]
To be clear, this issue wasn't solved. It's a feature request.
