### ISSUE TITLE
Plug mini (US) API value electricCurrent is wrong

### ISSUE THREAD

**Issue by yakumo-saki** [OpenWonderLabs/SwitchBotAPI#119]
### Analysis

Plug mini (US) API electricCurrent is not same as Switchbot Android app shows.

### Expected Behavior

* Value of electricCurrent is same as Switchbot Android app.
* Switchbot API electricCurrent should be "2.059" instead of "20.59"

### Steps To Reproduce

1. Launch Switchbot App in your smartphone.
2. Show detail of Plug mini
3. call Switchbot API `https://api.switch-bot.com/v1.0/devices/<plug_mini_deviceid>/status`
4. Current value of Switchbot App and API value of electricCurrent is not same. (eg: App 2.0A v. API 20.59A)

#### Switchbot API result

* "electricCurrent": 20.59

```json
{"statusCode":100,"body":{"deviceId":"**********","deviceType":"Plug Mini (US)","hubDeviceId":"**********","power":"on","voltage":102.2,"weight":202.3,"electricityOfDay":1026,"electricCurrent":20.59},"message":"success"}
```

#### Switchbot APP result

* APP shows current is "2.0A"
* Actual picture is in "Additional Context"

### Configuration

```json
* curl -X GET -H 'Authorization: ${TOKEN}' https://api.switch-bot.com/v1.0/devices
```

### Environment

- OS: Arch Linux
- Software: curl

### Additional Context

* Switchbot APP says "Current(電流) is 2.0A"

![](https://user-images.githubusercontent.com/1060869/181203432-848cac2c-9fed-48df-89cc-a8e8fa78f084.png)

**Comment by coocoo03** [comment]
I have a same issue.
I hope to be resolve.

**Comment by mizuno-as** [comment]
I confirmed same issue by Plug Mini(JP).
Please re-open this issue.
