### ISSUE TITLE
Api Documentation for local control

### ISSUE THREAD

**Issue by niemyjski** [OpenWonderLabs/SwitchBotAPI#12]
Will this api documentation work for talking to your hub mini locally? Controlling the devices locally without the cloud is extremely important.

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @niemyjski , I'm sorry that it can't, and there is no such plan at present.

**Comment by niemyjski** [comment]
There is a wave in smart home tech to run local, would be great to be on board or provide HomeKit support :). Going forward I will not be buying any products that don't run local in some way shape or form. Having a local api immediately boosts that product to the top of my list even if it's not of the same quality

**Comment by strunker** [comment]
I agree, and I feel slightly misled because prior to purchasing I had read that the hub was rumored to have an API in development. And when I read that I thought cool its local to the hub. Then I read the docs and realized.. It wasn't..

**Comment by niemyjski** [comment]
I also opened #13

**Comment by niemyjski** [comment]
Same here, I previously opened #13 after this was closed but just opened a feature request (#19)
