### ISSUE TITLE
190 unknown error in app, but not through API

### ISSUE THREAD

**Issue by snthibaud** [OpenWonderLabs/SwitchBotAPI#122]
### Analysis

When sending IR commands to an air conditioner through a mini Hub, the app sometimes shows 190 unknown error, but the API returns no errors at all.
The command actually failed, but there is no way to see that through the API, so I cannot retry on failure.

### Expected Behavior

API should return 190 unknown error as well.

### Steps To Reproduce

Send many commands through an IR mini hub and wait until 190 unknown error happens (it happens sporadically).

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS: Debian Linux
- Software: Python app
- Node: -
- npm: -

### Additional Context

![6EC4E472-C18E-4071-86EE-80DDEB3DE740](https://user-images.githubusercontent.com/946663/182041846-e4a6c0ba-ce49-4675-bbfc-14c2f33114c9.png)

**Comment by trungnguyengk** [comment]
yes i have same bug, please help me @donavanbecker

**Comment by Plasmachef** [comment]
the same here with a mini hub and a bot.
please fix it, thank you :-)

**Comment by baty0man** [comment]
This should definitely show up as an error on the API. Sine error 190 and 161 are happening often.

**Comment by snthibaud** [comment]
This issue still occurs.

**Comment by baty0man** [comment]
It'd be great to know if this is something the Devs will eventually implement.

**Comment by RDDJ** [comment]
> the same here with a mini hub and a bot. please fix it, thank you :-)

Having this issue as well.

**Comment by snthibaud** [comment]
Hmm... can this be Re-opened? The issue has not been solved yet.

**Comment by snthibaud** [comment]
I will create a new ticket then...
