### ISSUE TITLE
State of the API

### ISSUE THREAD

**Issue by Plasmachef** [OpenWonderLabs/SwitchBotAPI#128]
### Current Situation

is there a webpage where I can see the state of the API?

At the moment the API (or the connection to switchbot-server) is down* and I'm wondering if I can see this state of the API somewhere.
It would help alot and I wouldn't blame my code for the failure.

Thank you

*17:00 CEST, August  8th 2022

### Logs

```markdown
no need
```

### Configuration

```json
no need
```

### Environment

no need

**Comment by miiton** [comment]
I want it too.

In my environment, the SwitchBot API seems to be malfunctioning from around 2022-08-26 09:00 UTC.

![image](https://user-images.githubusercontent.com/468745/187005802-e9da954e-dd7e-4080-b702-ce0b0e375ff6.png)

**Comment by blade3609** [comment]
The API isn't working for me either. I get null response now when i use my authorization. Did a reset of the authorization, rebooted the hub.. nothing worked.

**Comment by Minsheng** [comment]
Hello guys, we are really sorry for the inconvenience!
The API is back to normal. The incident took place from 2022-08-26 9AM UTC to 2022-08-27 12:50AM UTC.
Please refer to https://status.switch-bot.com/ for its operation status.
I will go ahead and close the issue. now
