### ISSUE TITLE
API Support for Ceiling Light

### ISSUE THREAD

**Issue by one6o** [OpenWonderLabs/SwitchBotAPI#129]
### Current Situation

Ceiling Light is not supported by API.  Is there any plans for this?

### Proposed Change

Ceiling Light should be supported by API similar to Color Bulb/Strip Light.
This would allow access to device properties including:
- on/off state
- brightness
- color temperature

**Comment by chenliuyun** [comment]
Hi, we're working on it.  Expect it in two weeks, thanks.

**Comment by chenliuyun** [comment]
It's available now. Thanks for your support.
