### ISSUE TITLE
Api Documentation for local control

### ISSUE THREAD

**Issue by niemyjski** [OpenWonderLabs/SwitchBotAPI#13]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Device Model:**

Hub Mini, Curtains, remote (e.g., all products).

# **SwitchBotAPI**

- **Use Case**:
Will this api documentation work for talking to your hub mini locally? Controlling the devices locally without the cloud is extremely important.

**Comment by donavanbecker** [comment]
@niemyjski This api is cloud based not local.

**Comment by strunker** [comment]
I too wish it talked directly to the hub. If switchbot was ever to go under, or the internet goes out, etc you still retain control. I do NOT like cloud based apis but that is how this one was designed unfortunately. Its likely a hardware limitation on the existing hubs. 

I can tell you the mobile app itself, also talks over the cloud it doesnt talk over your local network to the hub either. So right now everything they have designed is internet\cloud based.
