### ISSUE TITLE
Add a nonce to Request Header

### ISSUE THREAD

**Issue by hm0429** [OpenWonderLabs/SwitchBotAPI#130]
### Current Situation

When I requested to v1.1 API without a nonce, the API returned `{"message":"Unauthorized"}`.
With a nonce, the v1.1 API worked as expected.

I assume this behavior itself is intended.

### Proposed Change

Please add an explanation of a nonce to [Request Header](https://github.com/OpenWonderLabs/SwitchBotAPI/blob/main/README.md#request-header) section in the README.
Thanks!

**Comment by donavanbecker** [comment]
Submit PR, and I will accept

**Comment by chenliuyun** [comment]
The document has updated
