### ISSUE TITLE
An authentication error occurs.

### ISSUE THREAD

**Issue by coranini** [OpenWonderLabs/SwitchBotAPI#135]
### Analysis

It has a switchbot hub mini and curtains.
I received tokens and secret keys from the switchbot app and input them into the switchbot system device, but an authentication error occurs.
The Switchbot Hub Mini has two Switchbot curtains connected and the cloud service is also on.
I tried initializing the hub mini and reinstalling the app, but it's frustrating because it doesn't work.

It was the same even if you regenerated the token and entered it.
The app version is 6.14.

What did I do wrong?

![image](https://user-images.githubusercontent.com/70638513/193175137-1f5d8cd3-6d96-4717-ad7a-1702de99f3f8.png)
![image](https://user-images.githubusercontent.com/70638513/193175179-cf3da226-1335-4052-991a-debe7091e654.png)
![image](https://user-images.githubusercontent.com/70638513/193175227-c9db2428-d83c-4b65-b9f8-db203c71454b.png)

### Expected Behavior

There is no authentication error.

### Steps To Reproduce

1. Install hub mini and curtain on switchbot application.
2. Connecting the Switch Curtain Cloud Service
3. Tap the app version continuously to receive the token value
4. Add hubitat driver code and install virtual device (switchbot system)
5. Enter token and secret key value into switchbot system device

### Logs

```markdown
dev:1682022-09-30 11:16:52.333 am debuginitialize() failed: status code: 401, reason phrase: Unauthorized
dev:1682022-09-30 11:16:52.332 am debugreadDevices() failed: status code: 401, reason phrase: Unauthorized
dev:1682022-09-30 11:16:52.331 am debughttpGetExec() failed: status code: 401, reason phrase: Unauthorized
dev:1682022-09-30 11:16:51.448 am debughttpGetExec([uri:https://api.switch-bot.com/v1.1/devices, headers:[Authorization:﻿  , Content-Type:application/json; charset=utf8, t:1664504211447, sign:XC+KYQSIQUWMOU+BNWQEIMHXQYJMEWZI/PJPV14SQC8=, nonce:]])

Token has been deleted.
```

### Configuration

```json
.
```

### Environment

- OS: Hubitat C7 2.3.2.141
- Software:
- Node:
- npm:

**Comment by donavanbecker** [comment]
@coranini you can look at the beta branch of [homebridge-switchbot](https://github.com/OpenWonderLabs/homebridge-switchbot) plugin to see how I implemented the new API. I have had success doing it.

**Comment by coranini** [comment]
> @coranini you can look at the beta branch of [homebridge-switchbot](https://github.com/OpenWonderLabs/homebridge-switchbot) plugin to see how I implemented the new API. I have had success doing it.

I'm still a beginner and I'm using Hubitat, so I didn't understand what you said.

**Comment by tomwpublic** [comment]
@coranini , does it with now if you try again to refresh your token and key?

It seems like there was a temporary outage with the SwitchBot API sometime in the last few days, based on a couple of reports on the Hubitat forum that now seem resolved.
