### ISSUE TITLE
Switchbot API Response

### ISSUE THREAD

**Issue by dylanmunro81** [OpenWonderLabs/SwitchBotAPI#145]
### Current Situation

I'm using the SwitchBot API to trigger my switchbot to press a button. On occasion this doesn't work and when I check the logs against the SwitchBot Hub Mini in the app it shows different errors when it doesn't work such as unknown error or Connection error. The thing is though, the Switchbot API returns a Status Code of 100 and "Success" each and every time, regardless of whether the action has been successful or not. Is there any way to have the API respond with the actual status of the request so if need be I can automatically retry the request again?

### Logs

```markdown
• Press
3:56 pm Unknown error (190)
Press
3:54 pm Executed successfully
Press
3:54 pm Executed successfully
Press
3:40 pm Executed successfully
Press
3:40 pm Executed successfully
Press
3:19 pm Executed successfully
• Press
3:17 pm Connection error (161)
• Press
11:26 am Unknown error (190)
• Press
11:25 am Connection error (161)
```

### Configuration

```json
{
    "command": "press",
    "parameter": "default",
    "commandType": "command"
}
```

### Environment

- OS: Mac OS
- Software: Postman
- Node:
- npm:

**Comment by asknoone** [comment]
I have only started using the API today but I am finding it not very reliable. Would be good to know if this is common or just a current issue today?

I too have seen error 190, but most commonly getting "Task timed out after 10.02 seconds".

Perhaps the Switchbot API is under-resourced or someone is hammering it?

**Comment by Write** [comment]
It's Unauthorized half of the time, and time out a lot of the time.
It's really awefull.

**Comment by Plasmachef** [comment]
Look [here](https://github.com/OpenWonderLabs/SwitchBotAPI/issues/122) this isn't a new problem

**Comment by baty0man** [comment]
Can we re-open this issue?
