### ISSUE TITLE
How to get API v1.0 tokens if I'm still using older products only?

### ISSUE THREAD

**Issue by vimalbhaya** [OpenWonderLabs/SwitchBotAPI#158]
### Current Situation

Hi,

How can one generate API v1.0 style tokens if I'm using older products only? The new app generates two sets.

Or, will the token portion itself be enough to authenticate in api v1.0 ?

Thanks

Vimal

### Logs

```markdown
Not applicable
```

### Configuration

```json
Not applicable
```

### Environment

IOS - v 6.18.1

**Comment by iCarrot0605** [comment]
The v1.0 token is the same as the v1.1 token.
