### ISSUE TITLE
Python; trying to use POST to open a curtain

### ISSUE THREAD

**Issue by nigels0** [OpenWonderLabs/SwitchBotAPI#16]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Device Model:**

# **SwitchBotAPI**

I'm stumped trying to close a curtain.

I'm using the following headers and params, but I'm getting the following error:
{u'body': {}, u'message': u'param is invalid', u'statusCode': 190}

`HEADERS = {'Content-Type': 'application/json; charset=utf8',
'Authorization': '{0}'.format(API_KEY)}
turnOff = {'command':'turnOff'}
turnOn = {'command':'turnOn'}

def set_devices_info(url, params):
response = requests.post(url, headers=HEADERS, params=params)
if response.status_code == 200:
return json.loads(response.content.decode('utf-8'))
else:
return None
`

the URL is correct as per the docs.

Anyone have any thoughts what I'm doing wrong?

**Comment by strunker** [comment]
you need to do use json= as the body in the post.

See my implementation below.
`
botToken = 'INSERT YOUR PERSONAL TOKEN HERE'
botHeader = {'Authorization':botToken,'Content-Type':'application/json; charset=utf8'}
bedroomCurtain = 'INSERT UNIQUE DEVICE ID HERE'
livingroomCurtain = 'INSERT UNIQUE DEVICE ID HERE'
openCurtains = {'command':'turnOn'}
closeCurtains = {'command':'turnOff'}

def SwitchBotCommand(command):
    command = command.lower()
    if "living" in command:
        localRoom = livingroomCurtain
        localroomText = "living room"
    elif "bed" in command:
        localRoom = bedroomCurtain
        localroomText = "bedroom"
    else:
        print("SwitchBot Problem: {} Is Not A Valid Room.".format(command))
        return("Bad-You stated an invalid room, please try again.") 
    try:
        if "open" in command:
            data = api.post('https://api.switch-bot.com/v1.0/devices/{}/commands'.format(localRoom),headers=botHeader,json=openCurtains)
            return("Good-Opening {} curtain.".format(localroomText))
        elif "close" in command:
            data = api.post('https://api.switch-bot.com/v1.0/devices/{}/commands'.format(localRoom),headers=botHeader,json=closeCurtains)
            return("Good-Closing {} curtain.".format(localroomText))
        else:
            print("SwitchBot Problem: {} Is Not A Valid Command.".format(command))
            return("Bad-You stated an invalid command, please try again.")
    except Exception as E:
        print("SwitchBot Error: {}".format(E))
        return("Bad-There was an error talking to the SwitchBot.")
`

**Comment by nigels0** [comment]
That’s exactly it! Thanks.

my command changed to:

>`response = requests.post(url, headers=HEADERS, params=params) `

**Comment by strunker** [comment]
> That’s exactly it! Thanks.
> 
> my command changed to:
> 
> > `response = requests.post(url, headers=HEADERS, json=params) `

Very good :) you may want to mark your issue resolved and close at this point. TY
