### ISSUE TITLE
Use Hub Mini 415 error

### ISSUE THREAD

**Issue by DinaShen12** [OpenWonderLabs/SwitchBotAPI#161]
### Current Situation

I used the hub mini to access the api on postman, and successfully obtained all the devices, but I can’t see the status of the device and can’t use commands to control it, and it will have a 415 error. I want to know if my device does not support get Device status and send device control commands.

successfully obtained all the devices
![image](https://user-images.githubusercontent.com/119665802/205273126-3a28bec5-0344-454b-b9ca-370f31eac677.png)
get device status: no information in body
![image](https://user-images.githubusercontent.com/119665802/205273507-4160a41f-0786-425d-89de-2062b59a3c75.png)
send device control commands: 415 error
![image](https://user-images.githubusercontent.com/119665802/205274078-b424cf88-8f34-40ce-898c-29d78e4fc3dd.png)

### Logs

```markdown
{
    "message": "Unsupported Media Type"
}
```

### Configuration

```json
command: turnOn
```

### Environment

- OS: Windows 10
- Software: Postman
- Node:
- npm:

**Comment by adomigar** [comment]
Hi Dina!

In the last request you must enter the deviceID of the infrared device you want to turn on, not the deviceID of the SwitchBot.
