### ISSUE TITLE
Plug Mini Status electric current off by factor of 10

### ISSUE THREAD

**Issue by Jackalopalen** [OpenWonderLabs/SwitchBotAPI#163]
### Analysis

Response from status request on a plug mini device (both us and JP) gives an electric current value almost exactly 10 times higher than it should be (in amps).

### Expected Behavior

GET status of Plug mini device.

Receive response with accurate electric current value.

### Steps To Reproduce

GET status of Plug mini device.

Receive response with an electric current value 10 times that expected.

### Logs

```markdown
Following is an example response from a plug that is powering my dryer:

{
    "statusCode": 100,
    "body": {
        "deviceId": "id",
        "deviceType": "Plug Mini (US)",
        "hubDeviceId": "hubid",
        "power": "on",
        "voltage": 97.6,
        "weight": 528.8,
        "electricityOfDay": 820,
        "electricCurrent": 53.27
    },
    "message": "success"
}

Voltage and Wattage (weight) are as expected. Current is wildly off. As {P = V * I} you would expect current should be 828.8W/97.6V = 5.41A.
```

### Configuration

```json
https://api.switch-bot.com/v1.1/devices/{{device_id}}/status
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by iCarrot0605** [comment]
I have same problem.

**Comment by lostllama** [comment]
I have the same issue. This should be reopened.
