### ISSUE TITLE
API Token and secret do not work

### ISSUE THREAD

**Issue by gevgev** [OpenWonderLabs/SwitchBotAPI#166]
### Current Situation

I am getting 401 Unauthorized when trying the token and secret I got from the app with the simple example code provided in readme. I have tried C# and Python3 examples, in both cases I am getting 401 Unauthorized.

Here is my code (C#):
```using System.Net.Http.Headers;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
 
string token = "xxxxxxxxxxxxx";
string secret = "xxxxxxxxxxxxx";
DateTime dt1970 = new DateTime(1970, 1, 1);
DateTime current = DateTime.Now;
TimeSpan span = current - dt1970;
long time = Convert.ToInt64(span.TotalMilliseconds);
string nonce = Guid.NewGuid().ToString();
string data = token + time.ToString() + nonce;
Encoding utf8 = Encoding.UTF8;
HMACSHA256 hmac = new HMACSHA256(utf8.GetBytes(secret));
string signature = Convert.ToBase64String(hmac.ComputeHash(utf8.GetBytes(data)));
 
//Create url
string url = "https://api.switch-bot.com/v1.1/devices";
 
//Create http client
HttpClient client = new HttpClient();
client.DefaultRequestHeaders.Add("Accept", "*/*");
client.DefaultRequestHeaders.Add("Authorization", token);
client.DefaultRequestHeaders.Add("sign", signature);
client.DefaultRequestHeaders.Add("nonce", nonce);
client.DefaultRequestHeaders.Add("t", time.ToString());
HttpResponseMessage response = await client.GetAsync(url);
var content = await response.Content.ReadAsStringAsync();
Console.WriteLine(content);```

And here is an attempt to execute the above:
```
~/git/switchbot$ dotnet run
{"message":"Unauthorized"}
```

### Logs

```markdown
no logs, just the error.
```

### Configuration

```json
this is command line code, no additional config
```

### Environment

- OS: MacOS
- Software: C# .net Core 7.0.100

**Comment by iCarrot0605** [comment]
I wrote that example. And in my environment(Linux mint), that program worked.
But in another environment, there is some glitch.(See issue #137 )
A corrected version has been posted.It worked in my environment too.

Try this
```c#
using System;
using System.Diagnostics;
using System.Text;
using System.Security.Cryptography;
using System.Net.Http;

string token = "xxxxxxxxxx";
string secret = "xxxxxxxxxx";
DateTime current = DateTime.UtcNow;
var dt1970 = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
var time = current.ToUniversalTime().Subtract(dt1970).TotalMilliseconds;
string nonce = Guid.NewGuid().ToString();
string data = token + time.ToString() + nonce;
Encoding utf8 = Encoding.UTF8;
HMACSHA256 hmac = new HMACSHA256(utf8.GetBytes(secret));
string signature = Convert.ToBase64String(hmac.ComputeHash(utf8.GetBytes(data)));

//Create http client
HttpClient client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, @"https://api.switch-bot.com/v1.1/devices");
request.Headers.TryAddWithoutValidation(@"Authorization", token);
request.Headers.TryAddWithoutValidation(@"sign", signature);
request.Headers.TryAddWithoutValidation(@"nonce", nonce);
request.Headers.TryAddWithoutValidation(@"t", time.ToString());

var response = await client.SendAsync(request);

Console.WriteLine(await response.Content.ReadAsStringAsync());
```

**Comment by nebduj** [comment]
I'm using the Python3 example and getting intermittent failures.  I am creating a unique UUID per request for the nonce using this code:
 
    import uuid 
 
   api_info=(XXXX)   

    nonce = uuid.uuid4()
    t = int(round(time.time() * 1000))
    string_to_sign = '{}{}{}'.format(api_info['token'], t, nonce)
    string_to_sign = bytes(string_to_sign, 'utf-8')
    secret = bytes(api_info['secret'], 'utf-8')
    sign = base64.b64encode(hmac.new(secret, msg=string_to_sign, digestmod=hashlib.sha256).digest())
    print ('Authorization: {}'.format(api_info["token"]))
    print ('t: {}'.format(t))
    print ('sign: {}'.format(str(sign, 'utf-8')))
    print ('nonce: {}'.format(nonce))

    url = api_info['url'] + '/v1.1/devices'
    headers={'Content-Type': 'application/json',
        'Authorization': "{}".format(api_info["token"]),
        'sign':"{}".format(sign),
        't':"{}".format(t),
        'nonce':"{}".format(nonce)
    }
    response = requests.get(url, headers = headers)

and getting intermittent failures.  More failures than success but it does sometimes work.  Not sure what to do as I don't get any more feedback than unauthorized.

**Comment by iCarrot0605** [comment]
@nebduj The 'sign' in headers should be utf-8.
Try
```
-    'sign':"{}".format(sign),
+    'sign':"{}".format(str(sign, 'utf-8')),
```

**Comment by nebduj** [comment]
This seems to have been the issue.  Working consistently now.
