### ISSUE TITLE
Error 401 after 24Hours BAN

### ISSUE THREAD

**Issue by Neoakira** [OpenWonderLabs/SwitchBotAPI#170]
### Current Situation

Hello,

I use your API to manage bots but i make an error with my config and i pool too much the API. So i was ban for 24h but now i get error 401 unauthorized.

It's since 7 days i can't use API.

I don't know who can help me please.

Thanks.

Neo

### Logs

```markdown
[DEBUG] statusCode: 401
[DEBUG] Unknown statusCode, Submit Bugs Here: https://tinyurl.com/SwitchBotBug
```

### Configuration

```json
Homebridge
```

### Environment

- OS: Raspian
- Software: Homebridge
- Node:
- npm:

**Comment by donavanbecker** [comment]
Submit feedback into SwitchBot app

**Comment by Neoakira** [comment]
Hello,

I submit a feedback but…

« We would very much like to assist you, but the issue related to the open API is out of the capability of customer support, so we cannot provide a solid solution to you. According to our developers, any issue related to the open API should be followed up on GitHub. Please kindly submit an issue on GitHub. Here is the link you can visit »

Neo
