### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by ijt1234** [OpenWonderLabs/SwitchBotAPI#185]
### Current Situation

 I use my switchbot devices on homekit, through a switchbot plug in which creates a bridge between the switchbot app and homekit (Hoobs) running a Switchbot plug in. Every night some time after 22.00 GMT I am unable to control any of my switchbot devices through homekit. A few hours later everything works again (or not). Switchbot says the reason for the problem is:" OpenApi has a usage limit of 10,000, including control/query operations, and they found you exceeded it."
My question to you is how can I stop the issue from happening without having to reduce the number of devices on my network. For example, can I get a second Switchbot mini hub (or the new Switchbot hub 2 when it comes out) in order to raise the limit of API requests I can make a day.
 

### Logs

```markdown
Please advise
```

### Configuration

```json
Please advise
```

### Environment

- OS:Please advise
- Software:Please advise
- Node:Please advise
- npm:Please advise

**Comment by AdyRock** [comment]
Getting another hub on the same account won't increase the limit as it is account based.
The only work around, which I think would be frowned upon, is to setup a second account, but then the devices would not be able to see each other for any automations created within each account. Although, if you could link all the accounts to the same HomeKit, then it could kind of join them together.

**Comment by ijt1234** [comment]
Thanks for your help. I was thinking along those lines too - two accounts but working under Homekit. I'll buy the new switchbot hub 2 when it comes out and give it a try.
