### ISSUE TITLE
Blind / Tilt battery value always 100

### ISSUE THREAD

**Issue by AdyRock** [OpenWonderLabs/SwitchBotAPI#190]
### Analysis

When fetching the the status of the Blind / Tilt devices the "battery" value is always 100, regardless of the battery state.

### Expected Behavior

I would expect the value to represent the battery charge value.

### Steps To Reproduce

Fetch the Blind / Tilt status from the API.

### Logs

```markdown
{
  "deviceId": "xxxxxxxxxxx",
  "deviceType": "Blind Tilt",
  "hubDeviceId": "xxxxxxxxxx",
  "version": 12,
  "calibrate": true,
  "battery": 100,
  "direction": "Down",
  "slidePosition": 0
}
```

### Configuration

```json
Just using the API.
```

### Environment

- OS:
- Software:
- Node:
- npm:
Not applicable

**Comment by AdyRock** [comment]
Any news when this will be fixed?

**Comment by Minsheng** [comment]
Sorry for the delay! Would you mind submit feedback from the SwitchBot app so we can debug a bit? Thanks!
You can say something like Blind Tilt OpenAPI breaks.

**Comment by AdyRock** [comment]
Done, thanks for looking into this.
