### ISSUE TITLE
Show Water Level on API

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/SwitchBotAPI#2]
Is there a way to show the water level of the humidifier through the API?

not that it has to show that it is at a certain percentage, but at least if it would say the humidifier is empty that would be helpful to display.

**Comment by Minsheng** [comment]
Hi, this is Davidson from the dev team.
It is possible to return if it is empty or not. We will add this feature in the next API update. Please stay tuned.

**Comment by donavanbecker** [comment]
@Minsheng awesome, Thanks You!

**Comment by donavanbecker** [comment]
unstale

**Comment by absolutelyNothing9** [comment]
I am definitely looking forward to this feature as well.

**Comment by Aekung** [comment]
Are there any update regarding the water level? It would be great to have this exposed as well so Homekit can finally notify whenever the water level is low.

Thanks.

**Comment by SwitchBot-Wonderlabs** [comment]
It has been updated, please check the latest API documentation.
Thank you.

**Comment by donavanbecker** [comment]
Thanks! This has been implemented into the latest version of @switchbot/homebridge-switchbot
