### ISSUE TITLE
GET /devices returns 401 Unauthorized

### ISSUE THREAD

**Issue by Cosmeen** [OpenWonderLabs/SwitchBotAPI#201]
### Analysis

GET /devices returns 401 Unauthorized using examples from documentation in python and nodejs

### Expected Behavior

returns a list of devices

### Steps To Reproduce

Used the documentation examples for nodejs and python3

### Logs

```markdown
Authorization: somethingHere
t: 1682006685959
sign: anotherThingHere
nonce: 606259e0-ae0d-40a8-90e1-367b149f2c35

Response: Error: 401
```

### Configuration

```python
# using example code from documentation
import json
import time
import hashlib
import hmac
import base64
import uuid
import requests

# Declare empty header dictionary
apiHeader = {}
# open token
token = 'token' # copy and paste from the SwitchBot app V6.14 or later
# secret key
secret = 'secret' # copy and paste from the SwitchBot app V6.14 or later
nonce = uuid.uuid4()
t = int(round(time.time() * 1000))
string_to_sign = '{}{}{}'.format(token, t, nonce)

string_to_sign = bytes(string_to_sign, 'utf-8')
secret = bytes(secret, 'utf-8')

sign = base64.b64encode(hmac.new(secret, msg=string_to_sign, digestmod=hashlib.sha256).digest())
print ('Authorization: {}'.format(token))
print ('t: {}'.format(t))
print ('sign: {}'.format(str(sign, 'utf-8')))
print ('nonce: {}'.format(nonce))

#Build api header JSON
apiHeader['Authorization']=token
apiHeader['Content-Type']='application/json'
apiHeader['charset']='utf8'
apiHeader['t']=str(t)
apiHeader['sign']=sign
apiHeader['nonce']=str(nonce)




# Send GET request
response = requests.get('https://api.switch-bot.com/v1.1/devices', headers=apiHeader)

# Check response status code
if response.status_code == 200:
    # Parse JSON response
    data = json.loads(response.text)
    print(data)
else:
    print('Error: {}'.format(response))
```

### Environment

- OS:  Armbian 23.02.2 Bullseye with Linux **5.15.93-sunxi**
- Software: python3
$ python3 --version
Python 3.9.2

### Additional Context

I've also tried the nodejs example with same results.
Before, I've used API v1.0 for a long time with no problems.

**Comment by jmtemmos** [comment]
Hi. I have exactly the same problem, which makes it unusable for me unfortunately.

switchbot.devices() or switchbot.client.get('devices') raises the same error

**Comment by strunker** [comment]
Not sure what to say here. I literally just copied this EXACT code and it works fine. You need to substitute the actual token / secret from the Switchbot app in order for this to work. But the sample is not the issue here, I helped update it, as it was incorrect originally.

**Comment by jmtemmos** [comment]
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

I'm using python 3.9.2 . The exact same code raises Error: <Response [401]>

Also tried with python-switchbot https://github.com/jonghwanhyeon/python-switchbot wrapper
Same error.

Regenerating new token might help ?

Thanks

**Comment by Cosmeen** [comment]
@jmtemmos thanks for the hint.
I've regenerated the token and now it works.

**Comment by jmtemmos** [comment]
@Cosmeen cool ! It did not work for me....

**Comment by jmtemmos** [comment]
> @Cosmeen cool ! It did not work for me....

I've tried again from another machine (x86), and it worked ! Then back to the initial pi, and ...it is working. Spurius correlation ?...
