### ISSUE TITLE
Plug Mini(JP) Status electricCurrent becomes 10 times larger when the corrent is over 11A.

### ISSUE THREAD

**Issue by akabekotan** [OpenWonderLabs/SwitchBotAPI#203]
### Analysis

Plug Mini(JP) Status electricCurrent becomes 10 times larger when the corrent is over 11A.

### Expected Behavior

Switchbot API ellectricCurret should be same as the current showed in SwitchBot App.

### Steps To Reproduce

Got electricCurrent value with API.

### Logs

```markdown
Switchbot API gives ellectricCurret as 115.76 when SwitchBot App shows the current as 11.6A.
```

### Configuration

```json
https://api.switch-bot.com/v1.1/devices/{{device_id}}/status
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by akabekotan** [comment]
It looks this won't happen when the current is below 10A.

**Comment by norihiro** [comment]
I can reproduce the issue.
The status shows below but the power is around 220 W and the current is 2.2A, so the current is almost 10 times than actual.
```
{'device_id': '70041D81B99E', 'device_type': 'plug_mini(_j_p)', 'hub_device_id': '70041D81B99E',
 'power': 'on', 'voltage': '99.8', 'weight': '219.2', 'electricity_of_day': 667, 'electric_current': '21.81', 'version': 'V1.5-1.5'}
```

**Comment by norihiro** [comment]
Is there any plan to resolve this issue?
