### ISSUE TITLE
Cannot set air conditioner in dry mode

### ISSUE THREAD

**Issue by snthibaud** [OpenWonderLabs/SwitchBotAPI#204]
### Analysis

When operating the air conditioner through the API, I understand that the 'setAll' command should be issued. However, that command requires a temperate and my air conditioner does not support temperatures in dry mode. Setting to dry mode does work through the app.

### Expected Behavior

Air conditioner goes on in dry mode.

### Steps To Reproduce

Run setAll command specifying dry mode on powerstate 'on' with any temperature

### Logs

```markdown
Where should this log come from?
```

### Configuration

```json
What configuration?
```

### Environment

- OS: Kubuntu 22.04
- Software: Switchbot API
- Node: None
- npm: None

**Comment by snthibaud** [comment]
It is a Mitsubishi Electric MSZ-GV2217-W air conditioner.

**Comment by snthibaud** [comment]
It is still a problem

**Comment by davidsak** [comment]
I have this exact same issue, has there been a resolution or a work around?
