### ISSUE TITLE
SwitchBot Lock is very slow to respond when integrated in Home Assistant

### ISSUE THREAD

**Issue by wardwolfram** [OpenWonderLabs/SwitchBotAPI#205]
### Analysis

I have integrated the switchbot lock with Home Assistant (  Home Assistant 2023.4.6 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230411.1) successfully, but the response to commands is extremely slow, at times it is ~15-20 seconds response after a lock/unlock command.

### Expected Behavior

After the command is issued to lock/unlock, a 1 second or less response takes place

### Steps To Reproduce

I have installed and uninstalled the BT & Switchbot Lock integration within HA multiple times with the same results - slow (15-20 second response times).

1. Issue a lock or unlock command.
2. Wait until response takes place ~ 15 seconds later.
NOTE: At times, if you issue multiple responses close together (1-5 seconds apart), the response of the lock / unlock action can be quick.  But after idle time, and a command to lock and unlock is issued, there is a ~15 delay for the action to take place.

### Logs

```markdown
I do not see any errors in the HA logs reporting about the Switchbot Lock.
```

### Configuration

```json
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:

switch:
  - platform: wake_on_lan
    broadcast_address: 10.0.21.39
    mac: a0:36:9f:a0:1f:ac
    name: "FramOFFICE2"
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Additional Context

Home Assistant 2023.4.6 
Supervisor 2023.04.1 Operating System 10.1 
Frontend 20230411.1 - latest

**Comment by donavanbecker** [comment]
This should be opened with home assistant.
