### ISSUE TITLE
How many limit on webhook calling

### ISSUE THREAD

**Issue by sobassy** [OpenWonderLabs/SwitchBotAPI#206]
### Current Situation

It's simple question, how many limit on webhook calling?
I understand the limit of rest API we call is 10000 per day. This limit also applies to webhook calling?

### Logs

```markdown
no logs.
```

### Configuration

```json
no context.
```

### Environment

no env.

**Comment by donavanbecker** [comment]
From what I am aware of, there is no limit on webhooks.

**Comment by sobassy** [comment]
@donavanbecker 

Thanks!
