### ISSUE TITLE
OIDC/OAuth OP/IdP Support

### ISSUE THREAD

**Issue by snakaya** [OpenWonderLabs/SwitchBotAPI#207]
### Current Situation

I need my token and secret for authentication.
I want to serve SwitchBot API service to 3rdParty(Relying Party), But they need provide their token and secret to me.

This is a seriously insecure. 

### Proposed Change

Each developers will became RPs of OIDC/OAuth, I don't need their secret, just need access token and id_token.
For that, you need to provide SwitchBot account as federated id of OIDC/OAuth.

**Comment by strunker** [comment]
The API is / was designed around individual users, and product owners, consuming the key. I wouldn't ever really expect this change to go through... And personally, I would rather see them localize the API and remove the need for what you describe all together, way before implementing OAuth.
