### ISSUE TITLE
SwitchBot api return "Too many request" error message

### ISSUE THREAD

**Issue by KannadukiAoi** [OpenWonderLabs/SwitchBotAPI#213]
### Current Situation

I encountered a 'Too many requests' error message from the API, and I also checked the error in the documentation, which states, 'The client has exceeded the number of requests allowed for a given time window.' So here are my questions:

1. What exactly is the maximum number of requests allowed, and how long is the time window for these requests?
2. Is there an alternative plan available where we can pay for the API usage fee instead of using it for free but with limitations?

We are attempting to integrate the SwitchBot product into our IoT platform so that we can implement automation logic based on the SwitchBot API. However, when we execute a batch of API calls as part of our automation logic, we receive a 'Too many requests' error. This limitation is hindering us as we plan to integrate over 100 devices into our IoT platform.

### Logs

```markdown
{
  statusCode: 190,
  body: {
  },
  message: "Too many Request",
}
```

### Configuration

```json
We are not able to config SwitchBot API
```

### Environment

- OS: Windows
- Software: Node js
- Node: 16.14.2
- npm: 8.5.0

**Comment by turadg** [comment]
I have the same question,
> What exactly is the maximum number of requests allowed, and how long is the time window for these requests?

(I normally wouldn't +1 with a comment but I'm doing so in order for the bot to know this isn't stale.)

**Comment by sobassy** [comment]
From reference (Readme.md),

> The amount of API calls per day is limited to 10000 times. Going over that limit will return "Unauthorized."

**Comment by KannadukiAoi** [comment]
> From reference (Readme.md),
> 
> > The amount of API calls per day is limited to 10000 times. Going over that limit will return "Unauthorized."
Thank you for mation it, I read the Readme.md already before I post this issue. 
I believe 10,000 times is for one day. My usage if far from 10,000. But I call the api maybe 5 different api in 1 second for automation logic then it return "Too many request" error. There is other limitation also in Readme.md which is: "The client has exceeded the number of requests allowed for a given time window."

So, it is not about the total call for one day, it is for total call for one "time window". I guess the time window is about 2~3 minutes and limited it to maybe 3 api call which make this api not sutable for advance usage
