### ISSUE TITLE
Contact and Motion Sensor Webhook Delays

### ISSUE THREAD

**Issue by kevin-chowmain** [OpenWonderLabs/SwitchBotAPI#214]
### Current Situation

I am using the Webhooks API for the contact/motion sensor and have a question that I hope you can help me with:

Noticing up to a minute in delays of events being sent to my webhook url. 

Looking at the Switchbot app, the events are registered almost instantly. I also tested my url by sending the POST request manually and it receives the request almost instantly. 

### Proposed Change

Not sure if this is by design or only happening for me? 

With the contact and motion sensors, events would ideally need to be almost instant. Are there any improvements that can be done here?

**Comment by kevin-chowmain** [comment]
To clarify, its not always delayed... But very inconsistent... sometimes its very quick (2-5 seconds) and sometimes its up to a minute

**Comment by himphen** [comment]
It seems that the issue is not limited to both sensors. Recently, turning my light bulb off webhook has also experienced significant delays, and there are some events that have been dropped.
