### ISSUE TITLE
SwitchBot Hub Mini 4E no longer working through API

### ISSUE THREAD

**Issue by oatzjackz** [OpenWonderLabs/SwitchBotAPI#216]
### Current Situation

I've been using a SwitchBot Hub Mini 4E for more than a year to automate my AC. It's operated through HomeAssistant using the API.

Since a few days, the SwitchBot no longer reacts to input through the API. It still works through the phone app, but I need the API to work for my automatisations.

Has there been any change to the API or configuration recently?

When I operate it through curl commands, I get success messags but the SwitchBot still doesn't react. For example:

curl -X POST -H "Authorization: [authorisation token]" https://api.switch-bot.com/v1.0/scenes/[scene id]/execute

==> {"statusCode":100,"body":{},"message":"success"}

Thanks a lot in advance for your help!

### Logs

```markdown
Logs show how the device has received automated requests until a few days ago but no longer since.
```

### Configuration

```json
Switchbot Hub Mini 4E
```

### Environment

- OS: Android/Windows 11/HomeAssistant OS
- Software:
- Node:
- npm:

**Comment by Murianwind** [comment]
Me too.

**Comment by oatzjackz** [comment]
Since yesterday, everything is working fine again. No changes on my side. Seems like the problem was with Switchbot.
