### ISSUE TITLE
blind tilt batteries SOC  always 100%

### ISSUE THREAD

**Issue by LivingMachine00** [OpenWonderLabs/SwitchBotAPI#218]
### Current Situation

generating a request with this headers:       
 headers = {
            'Authorization': token,
            't': str(t),
            'sign': sign,
            'nonce': nonce,
            'Content-Type': 'application/json',
            'Cache-Control': 'no-cache'
        }

### Logs

```markdown
the api answer is 
{'statusCode': 100, 'body': {'deviceId': '', 'deviceType': 'Blind Tilt', 'hubDeviceId': '', 'version': 20, 'calibrate': True, 'battery': 100, 'direction': 'Down', 'slidePosition': 50}, 'message': 'success'}
```

### Configuration

```json
python script upon switchbot api
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Additional Context

and soc =100%, while I know from companion app  soc =70%
I used this value:
'Cache-Control': 'no-cache'
something missing?

**Comment by MikeDev96** [comment]
+1 mine are all reporting 50% despite mobile app providing accurate values.

**Comment by LivingMachine00** [comment]
> +1 mine are all reporting 50% despite mobile app providing accurate values.

same four me
