### ISSUE TITLE
SwitchBot Curtains - Pause Command

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/SwitchBotAPI#22]
**Is your feature request related to a problem? Please describe.**

Can't pause curtains with API

**Describe the solution you'd like**

Add pause command to API to be able to pause curtains

**Describe alternatives you've considered**

Just open or close curtains but that's not fun... 😀 
**Additional context**

SwitchBot App has it.
<a><img src="https://user-images.githubusercontent.com/9875439/104798635-15f0b080-578e-11eb-8666-90c0091061cd.png" width="250px"></a>

**Comment by DJay-X** [comment]
For example in the Eve App and with IKEA curtains, there is a stop button showing. When available by API this would be great to have in the SwitchBot Plug-in. Thx. 

![image](https://user-images.githubusercontent.com/3874239/104798879-a0ef9c00-57ca-11eb-91d5-575edfdaaa2a.png)

![image](https://user-images.githubusercontent.com/3874239/104798881-a947d700-57ca-11eb-8ac0-e86a4da328cf.png)

**Comment by avworldme** [comment]
This is a very necessary feature in the API.  Any update on when this will be added?

**Comment by ryingg** [comment]
I'm also looking to use a pause / stop curtain command with the API. Are there any updates?

**Comment by mthoretton** [comment]
I just tried with `{"command": "pause"}` works fine 😄

**Comment by donavanbecker** [comment]
@mthoretton must of been added in v1.1 of the API?

**Comment by mthoretton** [comment]
Maybe, I just learned about this github project 1h ago 😃

**Comment by mthoretton** [comment]
@donavanbecker Thanks for maintaining this project. Everything was super easy to setup and works smoothly! 👍 I tried the pause command many times already, as far as I can tell this issue is fixed. This is the hardware I have in case that's relevant: https://us.switch-bot.com/products/switchbot-curtain-u-rail-2

**Comment by strunker** [comment]
@donavanbecker  this is a documentation problem I just confirmed the above works Ill do a PR against the docs to get this added.

**Comment by strunker** [comment]
Opened https://github.com/OpenWonderLabs/SwitchBotAPI/pull/270 to get pause added to documentation. It does in fact work in v1.1 api I just tested. @donavanbecker  @mthoretton
