### ISSUE TITLE
(IR devices HUB) Device-specific commands.

### ISSUE THREAD

**Issue by SiriosDev** [OpenWonderLabs/SwitchBotAPI#222]
### Current Situation

Using the Swicthbot app I noticed that in some of my IR devices "connected to the hub" some new commands have been "enabled", (example in my Air Conditioner a command appeared that handles horizontal swing and a "different" auto mode), now I notice all the various possible requests to the api are default (related to example `{temperature},{mode},{fan speed},{power state}`).

### Proposed Change

It would be useful to be able to manage somehow the specific commands of some devices (such as just swing)

**Comment by SiriosDev** [comment]
unstale

**Comment by mrlt8** [comment]
Would like to see this get added as well so we can add [SwingMode](https://developers.homebridge.io/#/characteristic/SwingMode) to homberidge-switchbot.

**Comment by SiriosDev** [comment]
not stale

**Comment by SiriosDev** [comment]
not stale

**Comment by SiriosDev** [comment]
Not stale

**Comment by SiriosDev** [comment]
Not stale

**Comment by SiriosDev** [comment]
Nope

**Comment by SiriosDev** [comment]
nope

**Comment by SiriosDev** [comment]
not stale but ok
