### ISSUE TITLE
Report of 1000 Open API Polls

### ISSUE THREAD

**Issue by Ash347wa** [OpenWonderLabs/SwitchBotAPI#223]
### Current Situation

I have Switchbot open API app in Hubitat smart hub.

It states that it is limited to 1000 polls per day per Switchbot.

I have 20+ switchbot devices which means that I can only update status of each device roughly every 30 mins very minimum. Which of course makes the integration non-functional.

When I have tried polling the devices less than this time, the API integration stops working after a time as I assume more than 1000 polls have been made.

Is there a way to significantly increase the amount of available polling, else I would need to replace switchbot devices with other manufactures.

Hoping for some good news.

### Logs

```markdown
None
```

### Configuration

```json
None
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by donavanbecker** [comment]
Hubitat would either have to incorporate the webook connection which doesn't use the 10,000 rate limit, or BLE connection.
