### ISSUE TITLE
 Know the status of IR devices

### ISSUE THREAD

**Issue by goodsale** [OpenWonderLabs/SwitchBotAPI#224]
### Current Situation

With API 1.1 it is possible to pilot an air conditioner and send the relative commands but not know the status.

### Proposed Change

We ask to know the status of an IR device and in the case of an air conditioner, the answer should contain the mode, the set temperature, etc.

It is necessary because, for example, if an integration is created in Home Assistant that pilots the air conditioner, if the air conditioner is turned on by the Switchbot APP or by a voice command, Home Assistant is not able to update the status.

Thanks

**Comment by mrlt8** [comment]
I recently added temperature and humidity support for the IR Air-conditioner in Homebridge-switchbot: https://github.com/OpenWonderLabs/homebridge-switchbot/pull/761 and it would be much better if the IR devices could report the current status and any changes.
