### ISSUE TITLE
Curtain device pair detected as two plugs in Home Assistant

### ISSUE THREAD

**Issue by nwithan8** [OpenWonderLabs/SwitchBotAPI#226]
### Analysis

My pair of Curtain Rod v2 devices are incorrectly being auto-detected by Home Assistant's Bluetooth capabilities (and when manually added via the built-in SwitchBot integration) as two Plug Mini devices. I am unable to interact with the devices properly due to their misconfiguration (and they cannot be altered in Home Assistant from `switch` to `cover`)

<img width="183" alt="image" src="https://github.com/OpenWonderLabs/SwitchBotAPI/assets/17054780/3a4ffbaa-0c4c-4a9a-a64b-2eabe0ea0952">

In the SwitchBot app, the two devices paired together only offer one "Device Info", the MAC address of which matches the MAC address of the top entry in the screenshot above.

Log entry (days later when the device is assumedly not in active pairing mode)
<img width="1089" alt="image" src="https://github.com/OpenWonderLabs/SwitchBotAPI/assets/17054780/db652f86-447b-4472-96f5-7b6899f2deb4">

### Expected Behavior

I would expect Home Assistant to auto-detect the devices as a single curtain device rather than two plug devices, as has been documented in various [online tutorials](https://youtu.be/7V71d8BBKqw?t=234).

### Steps To Reproduce

- Set up two SwitchBot devices using the SwitchBot app (Android), pairing them together so that they work as one unit (left and right).
- Confirm the pair are working in the SwitchBot app.
- Open Home Assistant with a Bluetooth dongle attached and Bluetooth capabilities enabled.
- The SwitchBot devices should be auto-detected as Plug Minis rather than a curtain device.

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS: Home Assistant Operating System 2023.7.2
- Software: N/A
- Node: N/A
- npm: N/A

**Comment by nwithan8** [comment]
This was not complete, quite the opposite, no one replied. Please update your bot configuration to not auto-close a ticket just because no one has responded to an initial report.

**Comment by donavanbecker** [comment]
If you are using the built in SwitchBot support in HomeAssistant then you need to open an issue on the HoemAssistant repo
