### ISSUE TITLE
Meter emitting events irregularly

### ISSUE THREAD

**Issue by nachocab** [OpenWonderLabs/SwitchBotAPI#228]
### Current Situation

I set up a webhook yesterday around 5pm for my Meter and I don't really understand the pace. I started out with 10-20 events per hour but it's gone down to 1 per hour. Here's a screenshot of the last 24 hours: 

<img width="478" alt="CleanShot 2023-07-24 at 16 09 45@2x" src="https://github.com/OpenWonderLabs/SwitchBotAPI/assets/27538/45fb34bf-90cb-4409-8896-1b91e2970fc9">

What conditions trigger an event?

Here's the first of the last 100 events (6:18):

![CleanShot 2023-07-24 at 16 18 21](https://github.com/OpenWonderLabs/SwitchBotAPI/assets/27538/9dc1a15b-03e6-440e-b58e-9aa0fe8996d5)

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

N/A

**Comment by kganjoo** [comment]
I am facing a similar problem with a switchbot plug mini ( US ). The website mentions that  events are triggered during any state change to the device. However I have noticed that events are getting missed randomly. No sure what the issue is
