### ISSUE TITLE
How many calls per day?

### ISSUE THREAD

**Issue by francescosabia** [OpenWonderLabs/SwitchBotAPI#229]
### Current Situation

Can I ask how many calls per day are? 10000?

### Logs

```markdown
No log needed
```

### Configuration

```json
No config needed
```

### Environment

- OS: IOS 
- Software:
- Node:
- npm:

**Comment by donavanbecker** [comment]
@francescosabia Depends on how many devices and if you are using webhooks or not

**Comment by francescosabia** [comment]
> @francescosabia Depends on how many devices and if you are using webhooks or not

I have 3 devices: lock - meter and bot and I have put on lock every 10 seconds - on bot every 2 minutes and on meter every 4 minutes. I don t know how to see if I use webhooks 🤷🏻‍♂️

**Comment by donavanbecker** [comment]
Well this is the API repo so are you direct connecting with these details or using something else? Like the Homebridge plugin?

Bot: we really don't get much in the status updates from the API, so this could be set to every 5 to 15 mins. [12 (60 mins/5 mins) calls in a hour) * 24 hours in a day = 288]

Meter: way are you needing an update on this every 4 seconds? Could this also be set to every 5 to 15 mins? [12 (60 mins/5 mins) calls in a hour) * 24 hours in a day = 288]

Lock: This I could see being needed sooner but even everything 30sec to a min would be good. 30seconds would equal 2,880 calls in a day (correct me if I am wrong) [2 calls per min * 60 mins in an hour * 24 hours in a day = 2,880]

Just with that you would be at 3,456 calls.

So adjust as needed.

**Comment by francescosabia** [comment]
> Well this is the API repo so are you direct connecting with these details or using something else? Like the Homebridge plugin?
> 
> Bot: we really don't get much in the status updates from the API, so this could be set to every 5 to 15 mins. [12 (60 mins/5 mins) calls in a hour) * 24 hours in a day = 288]
> 
> Meter: way are you needing an update on this every 4 seconds? Could this also be set to every 5 to 15 mins? [12 (60 mins/5 mins) calls in a hour) * 24 hours in a day = 288]
> 
> Lock: This I could see being needed sooner but even everything 30sec to a min would be good. 30seconds would equal 2,880 calls in a day (correct me if I am wrong) [2 calls per min * 60 mins in an hour * 24 hours in a day = 2,880]
> 
> Just with that you would be at 3,456 calls.
> 
> So adjust as needed.

Yes homebridge plugin I use. SwitchBot told me that are 10000 calls per day. For the meter I have 2 minutes no 4 seconds. I made some calculations an I am about 9500 calls per day so I am in

**Comment by donavanbecker** [comment]
Bot could be even longer the 5 mins, like every hour..

**Comment by francescosabia** [comment]
> Bot could be even longer the 5 mins, like every hour..

Sure.. but if I am in 10000 range it s ok
