### ISSUE TITLE
Device not registered in device list under new account

### ISSUE THREAD

**Issue by yamamoto95** [OpenWonderLabs/SwitchBotAPI#233]
### Current Situation

After creating a new account and registering a device in the SwitchBot app, the device does not appear in the "Get device list".
When I log in with a previously created account and register a device, it appears in the "Get device list".

### Logs

```markdown
Array
(
    [statusCode] => 100
    [body] => Array
        (
            [deviceList] => Array
                (
                )

            [infraredRemoteList] => Array
                (
                )

        )

    [message] => success
)
```

### Configuration

```json
none
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by kakura** [comment]
I encounter the same thing as well now😢

**Comment by akisoqls** [comment]
I created an account today, and I have the problem too. 
API server responses OK, but `deviceList` is always empty.
Is the problem is a temporary like a server error?

```javascript
console.log(res)
```
```
Response {
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers {
    "content-length": "87",
    "content-type": "application/json",
    date: "Fri, 25 Aug 2023 13:45:20 GMT",
    "x-amz-apigw-id": "***",
    "x-amzn-requestid": "***",
    "x-amzn-trace-id": "***"
  },
  ok: true,
  redirected: false,
  status: 200,
  statusText: "OK",
  url: "https://api.switch-bot.com/v1.1/devices"
}
```

```javascript
console.log(await new Response(res.body).text())
```
```
{"statusCode":100,"body":{"deviceList":[],"infraredRemoteList":[]},"message":"success"}
```

**Comment by hsakoh** [comment]
I was able to reproduce the issue.

The accounts created on August 8th(account1) did not experience the problem, 
while the accounts created on August 26th(account2) did.

From the scope of sniffing the communication of the Android app, the difference lies in the response of /prod/account/api/v1/user/userinfo. Specifically, there was a discrepancy in the botRegion value:

Account1 had botRegion=us.
Account2  had botRegion=ap.

This difference in botRegion could be a clue to the underlying cause of the issue.
Recent changes, such as adding new regions, may have confused OpenAPI's internal routing.
AP = (xxx.execute-api.ap-northeast-1.amazonaws.com)
US = (xxx.execute-api.us-east-1.amazonaws.com)

**Comment by Hi-Rosh** [comment]
The same issue has also occurred to me. All I get is an empty device list as a successful result. It's reproducible with API of v1.0  or v 1.1. I sent a feedback on this via App yesterday but  the case was closed with no reply. Hoping they will fix it soon.

**Comment by tyyoshida** [comment]
The same  has also occurred, too.

**Comment by Hi-Rosh** [comment]
The issue still persists.

**Comment by Hi-Rosh** [comment]
Now I can get the proper device list of mine. I'm wondering if a newly created account needed some time to get device list properly or just the API server got some issue but I can go on with APIs. Thanks anyway.

**Comment by akisoqls** [comment]
I was now able to access too on my enviroment. Thanks!
