### ISSUE TITLE
401 Unauthorized via API

### ISSUE THREAD

**Issue by Landsil** [OpenWonderLabs/SwitchBotAPI#235]
### Current Situation

I'm stuck with trying to connect to API from AppsScript.
I've double checked that my AppsScript code returns same signature as python 3 in examples.
I've rotated the secret few times
I've waited for a 24 at one point just in case token takes time to go live.

### Logs

```markdown
just Unauthorized
```

### Configuration

```javascript
// Get all tokens and codes from project properties
var scriptProperties = PropertiesService.getScriptProperties()
token = scriptProperties.getProperty("Switchbot_token")
secret = scriptProperties.getProperty("Switchbot_secret")

/**
switchbotAPI function to be called where needed
*/

function switchbotAPI(body, method, path) {
  const t = Date.now();
  const nonce = Utilities.getUuid
  const data = token + t + nonce;
  const signTerm = Utilities.computeHmacSha256Signature(data, secret);
  const sign = Utilities.base64Encode(signTerm);

  var body = JSON.stringify(body);
  var hostname = 'https://api.switch-bot.com'

  var options = {
    "method": method,
    "muteHttpExceptions": true,
    "headers": {
      "authorization": token,
      "sign": sign,
      "nonce": nonce,
      "t": t,
    },
  };

  url = hostname + path
  response = UrlFetchApp.fetch(url, options)
  return response
}

// Run this when you add new device to your home to get ID's
function switchbotGetDevice() {
  var body = ""
  var method = "get"
  var path = "/v1.1/devices"

  devices = switchbotAPI(body,method,path)
  Logger.log(devices)
}
```

### Environment

- OS: N/A
- Software: JavaScript / Apps Script
- Node: N/A
- npm: N/A

**Comment by hsakoh** [comment]
```
  var options = {
    "method": method,
    "muteHttpExceptions": true,
    "headers": {
      "authorization": token,
      "sign": sign,
      "nonce": nonce,
      "t": t.toString(),
    },
  };
```

**Comment by Landsil** [comment]
This doesn't work but logging `t` I've noticed that is not longer formatted correctly, before it was one long number 13 char long as it should, now it's 1.693471503955E12

So I will fix that and test with and without changing to string and be back.

**Comment by Landsil** [comment]
ok, everything works now.

it failed but I decided to extra print tokens I'm using and compare with what apps gives me and what I have in password manager.

Somehow last few characters of token were different, I guess I can't even trust copy paste.

So it seems like it was on my but having someone to reply helped a lot, thank you.
