### ISSUE TITLE
Wrong scripts to generate the signature

### ISSUE THREAD

**Issue by georgesdib** [OpenWonderLabs/SwitchBotAPI#237]
### Analysis

The scripts provided in the README to generate the signature are missing the crucial `toUpperCase` step outlined in the instructions. This step is needed for correct authentication.

### Expected Behavior

Add `toUpperCase` to the provided scripts.

### Steps To Reproduce

Run the script, and check if the authorisation works, and it does not. Then add the `toUpperCase` step, and then it works.

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

N/A

**Comment by donavanbecker** [comment]
Please submit pr
