### ISSUE TITLE
What about adding an Open API specification ?

### ISSUE THREAD

**Issue by SeraphicRav** [OpenWonderLabs/SwitchBotAPI#238]
### Current Situation

Currently, the spec is written as a markdown file.

### Proposed Change

Hey Switchbot Developers,

Let's talk about [Open API (formerly known as Swagger)](https://spec.openapis.org/oas/v3.1.0) and why it's worth considering for your API specifications, especially if you're using Markdown.

**Why Open API?**

First things first, Open API uses a YAML variant, which I highly recommend for readability. But let's get to the good stuff:

1. **Prettier Specs**: With Open API, your API specifications will look oh-so-pretty. It's like giving your code a fresh coat of paint. Clean, organized, and easy on the eyes: Example https://petstore.swagger.io/

2. **Automagic Goodies**: Imagine this - you make your specs in Open API, and voilà, it can automatically whip up client libraries and mock servers. No more tedious manual work. Plus, it's a lifesaver for testing: https://swagger.io/tools/swagger-codegen/

3. **It's Just Practical**: I'm not here to give you a sales pitch. I'm here to tell you that Open API is just plain practical. It's like having a Swiss army knife for your API documentation and testing needs.

So, give it a whirl. It might just become your new favorite tool. And hey, I'm not on the Open API payroll - this is just a friendly tip from one developer to another.

Happy coding!

**Comment by SeraphicRav** [comment]
Hello?

**Comment by SeraphicRav** [comment]
I do not really how to communicate with Switchbot, I went through the help desk once to ask them to look more often at Github, then said they would look at it more often, I did not see any change.

**Comment by dopenchills** [comment]
I also would like the OpenAPI description from SwitchBot as it would be very beneficial for developers.
 They can autogenerate API client with tools such as [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator) and [Microsoft Kiota](https://github.com/microsoft/kiota), which will save their time a lot.

And [README.md](https://github.com/OpenWonderLabs/SwitchBotAPI/blob/21ad8ec597ac45ae70107d10afaae0796abfd4ca/README.md?plain=1#L284) says this document is OpenAPI, but I think it is misleading.

I would appreciate it if SwitchBot team could provide OpenAPI description in the format of YAML or JSON!

**Comment by multimeric** [comment]
I've started work on an OpenAPI spec here: https://github.com/multimeric/SwitchBotOpenAPI. Feel free to help by providing example responses for your devices (I don't have very many), or by helping to document the `/commands` endpoints. 

Having an independent OpenAPI spec means we can add more precise descriptions to everything, and it also means we can describe any part of the API that doesn't align with the docs here.
