### ISSUE TITLE
No deviceType field for Curtain 3

### ISSUE THREAD

**Issue by AdyRock** [OpenWonderLabs/SwitchBotAPI#241]
### Analysis

When fetching the list of device from the API, the curtain 3 devices have no deviceType entry.

### Expected Behavior

A valid deviceType of something like "Curtain" or "Curtain3".

### Steps To Reproduce

Call the API entry to fetch the list of devices.

### Logs

```markdown
{
  "deviceList": [
    {
      "deviceId": "C1316F1469F6",
      "deviceName": "Curtain 3 F6",
      "enableCloudService": true,
      "hubDeviceId": "",
      "curtainDevicesIds": [
        "E517216B42B6",
        "C1316F1469F6"
      ],
      "calibrate": false,
      "group": true,
      "master": false
    },
    {
      "deviceId": "C2A87CFB7CD3",
      "deviceName": "Hub 2",
      "deviceType": "Hub 2",
      "enableCloudService": true,
      "hubDeviceId": ""
    },
    {
      "deviceId": "C7850DE4775B",
      "deviceName": "Contact Sensor 5B",
      "deviceType": "Contact Sensor",
      "enableCloudService": true,
      "hubDeviceId": "C2A87CFB7CD3"
    },
    {
      "deviceId": "E517216B42B6",
      "deviceName": "Curtain 3 B6",
      "enableCloudService": true,
      "hubDeviceId": "E8099027FE07",
      "curtainDevicesIds": [
        "E517216B42B6",
        "C1316F1469F6"
      ],
      "calibrate": true,
      "group": true,
      "master": true
    },
}
```

### Configuration

```json
Using Homey
```

### Environment

Homey

### Additional Context

Without the deviceType it is difficult to determine which driver to use. Currently, all I can do is assume the missing deviceType has to be the curtain 3 devices, but that can't be good.

**Comment by AdyRock** [comment]
Any news on when this will be fixed?

**Comment by AdyRock** [comment]
Bump

**Comment by Michael-B-23** [comment]
Bump

**Comment by alexbk66** [comment]
Bump

**Comment by D-Kalck** [comment]
I have exactly the same problem

**Comment by Minsheng** [comment]
This problem should have been fixed. Please check again.

**Comment by AdyRock** [comment]
Yes, I can now see the Device type is reported as "Curtains3".

Does this require a firmware update or will all curtain 3 units now report this?

**Comment by skarotech** [comment]
I am seeing the same issue with the Hub 2, missing deviceType
