### ISSUE TITLE
Response for "Get device status" is incorrect after updating the curtain firmware from V3.5 to V4.6

### ISSUE THREAD

**Issue by hsakoh** [OpenWonderLabs/SwitchBotAPI#244]
### Analysis

After updating the curtain firmware from V3.5 to V4.6, the following issues have been observed.

* The 'moving' status is now represented as a numerical value instead of a boolean.
* The 'battery' status now displays a value different from what is shown in the app (It used to match the app's reading when on V3.5).

### Steps To Reproduce

Call `Get device status` API

### Logs

```markdown
{
    "statusCode": 100,
    "body": {
        "deviceId": "FFF9xxxxxx63",
        "deviceType": "Curtain",
        "hubDeviceId": "CA08xxxxxx66",
        "calibrate": true,
        "group": false,
        "moving": false,
        "slidePosition": 100,
        "version": "V3.5",
        "battery": 44
    },
    "message": "success"
}
```
```
{
    "statusCode": 100,
    "body": {
        "deviceId": "FFF9xxxxxx63",
        "deviceType": "Curtain",
        "hubDeviceId": "CA08xxxxxx66",
        "calibrate": true,
        "group": false,
        "moving": 100,
        "slidePosition": 100,
        "version": "V4.6",
        "battery": 59
    },
    "message": "success"
}
```

**Comment by p-hyro-tenseiph** [comment]
was this solved?

**Comment by hsakoh** [comment]
It has not been fixed at this time.
![image](https://github.com/OpenWonderLabs/SwitchBotAPI/assets/20980395/d4c969c0-6205-45bd-a692-1707675967b5)

```
{
    "statusCode": 100,
    "body": {
        "deviceId": "FFF9xxxxxx63",
        "deviceType": "Curtain",
        "hubDeviceId": "CA08xxxxxx66",
        "calibrate": true,
        "group": false,
        "moving": 100,
        "slidePosition": 100,
        "version": "V4.6",
        "battery": 59
    },
    "message": "success"
}
```

**Comment by kaboemm** [comment]
Any update on this? 

![image](https://github.com/OpenWonderLabs/SwitchBotAPI/assets/141458551/1686bb9a-8402-4680-a54a-3f5aed96863d)

I still get wrong battery % readings on my switch bots. Running version 6.3

**Comment by hsakoh** [comment]
I checked again today and `moving` has changed from number to bool.

But the battery level is still the wrong value (59 fixed value?). The battery level is still at the wrong value (fixed value of 59?).

```json
{
    "statusCode": 100,
    "body": {
        "deviceId": "FFF9xxxxxx63",
        "deviceType": "Curtain",
        "hubDeviceId": "CA08xxxxxx66",
        "calibrate": true,
        "group": false,
        "moving": false,
        "slidePosition": 99,
        "version": "V4.6",
        "battery": 59
    },
    "message": "success"
}
```
