### ISSUE TITLE
SwitchBot in HomeKit sometimes turns on by itself

### ISSUE THREAD

**Issue by francescosabia** [OpenWonderLabs/SwitchBotAPI#246]
### Analysis

As I said in the tile the SwitchBot sometimes turns on itself in the home app without having any command or schedule

### Expected Behavior

It doesn’t turn itself on without command

### Steps To Reproduce

.

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by donavanbecker** [comment]
How is this related to the API?

**Comment by francescosabia** [comment]
SwitchBot customer care told me to open an issue here!Inviato da iPhoneIl giorno 26 set 2023, alle ore 15:04, Donavan Becker ***@***.***> ha scritto:﻿
How is this related to the API?

**Comment by donavanbecker** [comment]
> SwitchBot customer care told me to open an issue here!

Okay but why would the api be effecting it? I think you need to add more details like, is this with an integration that is using the API?

**Comment by francescosabia** [comment]
It is with matter integrationInviato da iPhoneIl giorno 26 set 2023, alle ore 18:40, Donavan Becker ***@***.***> ha scritto:﻿

SwitchBot customer care told me to open an issue here!

Okay but why would the api be effecting it? I think you need to add more details like, is this with an integration that is using the API?

**Comment by donavanbecker** [comment]
Matter Integration would have nothing to do with this API.

**Comment by francescosabia** [comment]
I know… but SwitchBot told me to write here.. sorry 🙏🏻Inviato da iPhoneIl giorno 26 set 2023, alle ore 22:17, Donavan Becker ***@***.***> ha scritto:﻿
Matter Integration would have nothing to do with this API.
