### ISSUE TITLE
Support for the indoor/outdoor meter from the Switchbot Cloud integration

### ISSUE THREAD

**Issue by fontainechristophe** [OpenWonderLabs/SwitchBotAPI#253]
### Current Situation

Is it possible to add support for the indoor/outdoor meter from the recent Switchbot Cloud integration?

### Proposed Change

Integration of Switchbot Cloud has been added in HA 2023.10
For the moment, the Switchbot plugs and IR appliances are integrated.
Is is possible to add other Switchbot devices, and in particular the indoor/outdoor meter? The bluetooth integration with Switchbot Bluetooth is not always working well.

**Comment by donavanbecker** [comment]
You would request this with HA.
