### ISSUE TITLE
Knowing when a Press has actually happened / order matters

### ISSUE THREAD

**Issue by reneroth** [OpenWonderLabs/SwitchBotAPI#258]
### Current Situation

I have two keys that need to be pressed in a specific order. The response of the `/command` endpoint is `success`, but it might still take several seconds until the button actually gets pressed. Is there a way for me to know when the button has been pressed, so I can trigger the second one? Or does the API make sure that commands are always executed in the order they're being sent?

### Logs

```markdown
n/a
```

### Configuration

```
2x SwitchBot Smart Switch Toggle
1x SwitchBot Hub Mini
```

### Environment

- OS: CentOS
- Software: own script
- Node: 18
- npm: n/a

**Comment by pisabird** [comment]
How can I receive a response via the API to determine if the SwitchBot Bot device is busy? In the app, I receive a 'bingo' when it is successful, or a notification that the device is busy in case of a failure.
But when I make an api call then I only get success 100, even if the bot is busy.

**Comment by reneroth** [comment]
> note to self and others looking for something like this: the predefined scenes seem to run the commands one-after-the-other, so if you know the order of keys you want to press in advance, you can set up a scene/automation in the app and trigger that from the API

note to self and others looking for something like this: one of the updates this year has caused the scenes to not be strictly in order anymore. you can try reducing the probability of out-of-sync button presses by adding the new "delay" step, but... eh.

**Comment by reneroth** [comment]
what's also beautiful is that the API will return "success" even when the button is offline (and has been offline for weeks)
