### ISSUE TITLE
Get history data from outdoor meter

### ISSUE THREAD

**Issue by marcoberri** [OpenWonderLabs/SwitchBotAPI#268]
### Current Situation

HI,
Is there an API to download all the data recorded on the outdoor meter?

Thank you.

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by marcoberri** [comment]
News please?

**Comment by TonySdevs** [comment]
I notice the app can download extensive history, so I am hoping the API will be extended to download history too.
