### ISSUE TITLE
SwitchBot Hub 2 Touch Buttons - On/Off State

### ISSUE THREAD

**Issue by o-in25** [OpenWonderLabs/SwitchBotAPI#278]
### Current Situation

I want to be able to set up a webhook that gets triggered when the Hub 2's touch buttons are turned on/off. This could be particularly useful for controlling non-SwitchBot smart devices (like a Phillps Hue for example). 

When the webhook is set up through the API, the Hub will send the current device state to the body of the response, and looks something like:

```
{
    "eventType": "changeReport",
    "eventVersion": "1",
    "context": {
        "deviceType": "WoHub2",
        "deviceMac": DEVICE_MAC_ADDR,
        "temperature":13,
        "humidity":18,
        "lightLevel": 19,
        "scale": "CELSIUS",
        "timeOfSample": 123456789
    }
}
```
The problem here, though, is that the response is stateless - we have no way of knowing what specific button had triggered this hook (i.e. if it was the "on" or "off" button). The docs are unfortunately a bit sparse on what the enum values of `eventType` are, but everything I've seen so far always has a value of "changeReport." If there were more values for the type of event, like `changeReportOn` and `changeReportOff` I could check the type of event and figure out which button it was from there. Another option would be adding an additional property to the `context` object, like `"touchButtonState:": 1` for the on button and `"touchButtonState:": 2`.

```
{
    "eventType": "changeReport",
    "eventVersion": "1",
    "context": {
        "deviceType": "WoHub2",
        "deviceMac": DEVICE_MAC_ADDR,
        "temperature":13,
        "humidity":18,
        "lightLevel": 19,
        "scale": "CELSIUS",
        "timeOfSample": 123456789,
        // ... 
        "touchButtonState": 1
    }
}
```

OR

```
{
    "eventType": <something to distinguish a button on/off press>
    "eventVersion": "1",
    "context": {
        "deviceType": "WoHub2",
        "deviceMac": DEVICE_MAC_ADDR,
        "temperature":13,
        "humidity":18,
        "lightLevel": 19,
        "scale": "CELSIUS",
        "timeOfSample": 123456789
    }
}
```

Without having some sort of internal state (which I would believe is possible, since the Hub itself has an option for turning off the display when the off button is pressed) I will need to keep the device state in memory or backing store. This would be somewhat trivial, but since webhook requests can be rate limited and have backoff times to prevent multiple requests, keeping the state external becomes much a more difficult task. 

If there's another way to do this without changing the API itself, I am all ears.

### Proposed Change

To solve this problem, there would need to be either:

-  An enum of different event types to distinguish between on/off press
- An added property to the `context` object that reports the button that was pressed.

**Comment by leopoldricard** [comment]
UP!

**Comment by leopoldricard** [comment]
Hey @o-in25, i had the same issue!
Definitely your recommendations are great!

I think you can make it work with IFTTT.
The SwitchBot integration works fine for button ON or OFF.

![Image](https://github.com/user-attachments/assets/fcddd982-beb5-4277-ab5a-f70996037bdd)

You can then add a webhook call for whatever your device is.
Hope it helps!
