### ISSUE TITLE
API returns misleading success message with old readings for offline sensor

### ISSUE THREAD

**Issue by sh969** [OpenWonderLabs/SwitchBotAPI#280]
### Analysis

Using the official SwitchBot API I get a status 100 success message when querying a outdoor temperature sensor. The API still returns old sensor readings as if they were recent. This is misleading because my database is being polluted with wrong data rendering the device useless.

### Expected Behavior

The expected behavior would be for the API to return an error message or a status indicating that the device is currently unreachable or offline. An accurate status response would help in implementing more reliable error handling and feedback mechanisms in applications using the API.

### Steps To Reproduce

1. Ensure the SwitchBot sensor device is offline or not reachable.
2. Send a command to the device using the SwitchBot API.
3. Notice that the API returns a success message despite the device being offline.

### Logs

```markdown
{'statusCode': 100,
 'body': {'deviceId': '...',
  'deviceType': 'WoIOSensor',
  'humidity': 49,
  'temperature': 21.3},
 'message': 'success'}
```

### Configuration

```json
import requests

switchbot_token = '...'
device_id = '...' # mac address of SwitchBot temp/outdoor sensor

headers = {
    'Authorization': switchbot_token,
    'Content-Type': 'application/json',
}

def check_device_online_status(device_id):
    url = f'https://api.switch-bot.com/v1.0/devices/{device_id}/status'
    
    response = requests.get(url, headers=headers)
    return response.json()

check_device_online_status(device_id)
```

### Environment

- OS: Linux
- Software: Python 3.10.13
- Node: n/a
- npm: n/a

**Comment by TonySdevs** [comment]
Your query is to the cloud, which gets updates via the hub. I don't think your API call talks to the sensors live at the point of query.

**Comment by sh969** [comment]
In the SwitchBot app you can see the online status of sensors and bots live. If the app can see it, so should the API.

**Comment by abmptit** [comment]
Hello,
I just open a similar issue.
Is there any update there ?
