### ISSUE TITLE
API document for Robot Vacuum shows wrong deviceType

### ISSUE THREAD

**Issue by AdyRock** [OpenWonderLabs/SwitchBotAPI#281]
### Analysis

The deviceType shown in the document is "Robot Vacuum Cleaner S1", but it seems it should be something like "WoSweeper".
The K10 is returning "WoSweeperMini".

### Expected Behavior

Show the correct deviceType in the document.

### Steps To Reproduce

Read the document and get the data from the device.

### Logs

```markdown
{
  "deviceId": "***********",
  "deviceType": "WoSweeperMini",
  "workingStatus": "ChargeDone",
  "onlineStatus": "online",
  "battery": 100
}
```

### Configuration

```json
NA
```

### Environment

- OS: NA
- Software: NA
- Node: NA
- npm: NA

**Comment by AdyRock** [comment]
Grr, this github-action is a real nuisance. Can someone disable the stupid thing as it is just alienating your users and hiding problems.

**Comment by XLTechie** [comment]
This seems unlikely to have been solved in last 10 days.
