### ISSUE TITLE
Historical data for devices such as outdoor meters

### ISSUE THREAD

**Issue by AndreaVen** [OpenWonderLabs/SwitchBotAPI#284]
### Current Situation

Currently, in devices such as outdoor meters, you can only get the instant values of humidity and temperature while in the app you can get a wider range of values e.g the temperature throughout the day.

### Proposed Change

It would be great if the status response would include all the values available from 00:00 of the current day in a field like dailyHumidity: Array and dailyTemperature: Array.
Again, thank you very much for the great API and for considering my request!

**Comment by XLTechie** [comment]
Activity...
