### ISSUE TITLE
API Daily Limit

### ISSUE THREAD

**Issue by sanderzw** [OpenWonderLabs/SwitchBotAPI#291]
### Current Situation

I get the following messages when I try to use the API for my home automations. I have no indication on wat is allowed. I use 1 switch and 5 curtain drivers. I like to implement more, but due to the limit I am hassitant to by new ones

* 2024-04-08T20:24:27.901Z
!!!!!! Curtains getHubDeviceValues: 190: Requests reached the daily limit (2347) API calls

* 2024-04-08T20:24:27.935Z
!!!!!! Bot getHubDeviceValues: 190: Requests reached the daily limit (2347) API calls

In my opinion I only send a few requests a day. 6 to start/close curtains and a few (max 15) to trigger a switch to start a vent.

I am using a developer app on Homey smarthome platform

### Logs

```markdown
* 2024-04-08T20:24:27.901Z
!!!!!! Curtains getHubDeviceValues: 190: Requests reached the daily limit (2347) API calls

* 2024-04-08T20:24:27.935Z
!!!!!! Bot getHubDeviceValues: 190: Requests reached the daily limit (2347) API calls
```

### Configuration

```json
-
```

### Environment

Homey

### Additional Context

-

**Comment by donavanbecker** [comment]
You need to open this issue on the Homey repo.

**Comment by sanderzw** [comment]
It is not related to homey. Switchbot support directed me to this thread. The limit is a response from switchbot

**Comment by donavanbecker** [comment]
> It is not related to homey. Switchbot support directed me to this thread. The limit is a response from switchbot

It is related to homey, because homey is requesting updates to the API and that is causing you to go over your daily limit.

**Comment by sanderzw** [comment]
I have maybe found the solution. I just het the message of the daily limit. After that I trijd the Repair option on the device in Homey. This requires me to login. After the repair the message was gone and the devices are working. what happens the comming days. I will keep you posted.
