### ISSUE TITLE
Curtain still not move but the reponse looks like have no problem.

### ISSUE THREAD

**Issue by hzx1987227** [OpenWonderLabs/SwitchBotAPI#3]
Hi there,

Yesterday i have setting up the API for my homeassistant and it worked for me with 3 curtain devices.
Today the api looks like broken but the result still success.

I tried use the Postman for test the API manually ,
Both https://api.switch-bot.com/v1.0/devices AND https://api.switch-bot.com/v1.0/devices/C60E256*****/status
are worked, But when i use https://api.switch-bot.com/v1.0/devices/C2F1406*****/commands to send the command,
curtain still not move but the reponse looks like have no problem.
{
    "statusCode": 100,
    "body": {},
    "message": "success"
}

Could you please take a look for me?

Thank you

=====UPDATE=======

When i rebooted the Hub mini, the API worked again,may be this is a bug for Hub mini or?

Thank you

**Comment by duceduc** [comment]
I am having issues as well but I am using curl over CLI. These commands works:
https://api.switch-bot.com/v1.0/devices
https://api.switch-bot.com/v1.0/statues

What isn't working for me is POST:
https://api.switch-bot.com/v1.0/devices/{mac}/turnOn

    {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=TOKEN"}

How are you setting the Authorization part in Postman? I am getting unauthorized error. I think I am not adding the token key correctly.

**Comment by hzx1987227** [comment]
> I am having issues as well but I am using curl over CLI. These commands works:
> https://api.switch-bot.com/v1.0/devices
> https://api.switch-bot.com/v1.0/statues
> 
> What isn't working for me is POST:
> [https://api.switch-bot.com/v1.0/devices/{mac}/turnOn](https://api.switch-bot.com/v1.0/devices/%7Bmac%7D/turnOn)
> 
> ```
> {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=TOKEN"}
> ```
> 
> How are you setting the Authorization part in Postman? I am getting unauthorized error. I think I am not adding the token key correctly.
> 
> **Edit**: I figured out how to properly add the token. I get this error using this url.
> [https://api.switch-bot.com/v1.0/devices/{MAC}/commands](https://api.switch-bot.com/v1.0/devices/%7BMAC%7D/commands)
> 
> What is the proper url to have the curtain fully open/close?
> 
> ```
> "statusCode": 190,
> "body": {},
> "message": "param is invalid"
> ```

You can add the following context to the body then select the raw with json format

{
    "command": "turnOn",
    "parameter": "default",
    "commandType": "command"    
}

**Comment by duceduc** [comment]
Getting this error now.

    "statusCode": 190,
    "body": {},
    "message": "ExpressionAttributeValues must not be empty"

[Error Message](https://ibb.co/QC3Mx3N)

**Comment by hzx1987227** [comment]
> Getting this error now.
> 
> ```
> "statusCode": 190,
> "body": {},
> "message": "ExpressionAttributeValues must not be empty"
> ```
> 
> [Error Message](https://ibb.co/QC3Mx3N)

Post Url is : 

https://api.switch-bot.com/v1.0/devices/C2F1406*****/commands

**Comment by duceduc** [comment]
This is my post URL
https://api.switch-bot.com/v1.0/devices/C5C6DFDH83EJ/commands

I have tried unchecking Content-Type. Still same error.

**Comment by hzx1987227** [comment]
![image](https://user-images.githubusercontent.com/14362669/103163592-b2ccc780-483a-11eb-9412-9c117eba05f6.png)
![image](https://user-images.githubusercontent.com/14362669/103163595-bfe9b680-483a-11eb-9342-3cfc58249489.png)
![image](https://user-images.githubusercontent.com/14362669/103163606-d132c300-483a-11eb-9d71-97df60b1891f.png)

Check the setting

**Comment by duceduc** [comment]
So weird. I am also using the curtain bot and matched your settings. Still error occurs.
Error code 190 is:
    190 | System error | Device internal error due to device states not synchronized with server

![](https://ibb.co/4KC9zL3)

**Comment by donavanbecker** [comment]
Check homebridge-switchbot-openapi, I haven't implemented curtains yet, but connection to API is solid

**Comment by hzx1987227** [comment]
> So weird. I am also using the curtain bot and matched your settings. Still error occurs.
> Error code 190 is:
> 
> ```
> 190 | System error | Device internal error due to device states not synchronized with server
> ```
> 
> [settings](https://ibb.co/4KC9zL3)

emmmm...

Try use SwitchBot App move your curtain first?

Then post the api?

I have no idea...

**Comment by hzx1987227** [comment]
> Check out: [homebridge-switchbot-openapi](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi), I haven't implemented curtains yet, but connection to API is solid.

When i rebooted the Hub mini, the command API worked again,may be this is a bug for Hub mini

**Comment by apetryk2** [comment]
I just wanted to point out that anyone that is getting the ExpressionAttributeValues must not be empty make sure to enable cloud service on your switchbot device.  I was getting this error and then when I enabled cloud services (via the app) the error went away.

**Comment by WintyBe** [comment]
Some extra info about the 'ExpressionAttributeValues' error as you'll probably end up here. It also occurs if you try to move a curtain in a group (2 curtains grouped together, for middle opening) and you're not moving the master curtain. Using the master's ID solves the issue.
