### ISSUE TITLE
Api reports an incorrect device for a ir remote device

### ISSUE THREAD

**Issue by ptrvg** [OpenWonderLabs/SwitchBotAPI#30]
**Describe The Bug:**

I added a infrared remote to the mini hub to control a Speaker. It did not work correctly in homebridge-switchbot-openapi. I noticed it mentioned an incorrect device id. I then tried it directly from the api and the device id looks weird there too:

`{"statusCode":100,"body":{"deviceList":[{"deviceId":"DD58D5B7FB3C","deviceName":"Hub Mini 3C","deviceType":"Hub Mini","hubDeviceId":"000000000000"},{"deviceId":"F0AE49955AD4","deviceName":"Open Bot","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"DD58D5B7FB3C"},{"deviceId":"FB3C5D545A86","deviceName":"Sluit Bot","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"DD58D5B7FB3C"}],"infraredRemoteList":[{"deviceId":"02-202103071019-45073334","deviceName":"Computer Speaker","remoteType":"DIY Speaker","hubDeviceId":"DD58D5B7FB3C"}]},"message":"success"}`

**To Reproduce:**

Add a new ir device to the mini hub. I used other and trained the remote. Then use the api to retrieve the device list

**Expected behavior:**

A correct device id.

**Screenshots:**

**Device Model:**

# **SwitchBotAPI**

- **Use Case**:

**Comment by DavidCPreston** [comment]
I noticed that yesterday, when I try to return the status I get status code 190 Invalid, BUT if I send a valid command to the device ID it works
