### ISSUE TITLE
API 1.0 Cannot read devices list

### ISSUE THREAD

**Issue by corasaniti** [OpenWonderLabs/SwitchBotAPI#312]
### Analysis

I get error with the API 1.0 which I have always used correctly via curl and also with the contrib nodered

`node-red-contrib-switchbot-api version 0.1.4`
https://flows.nodered.org/node/node-red-contrib-switchbot-api

Now I am not able to use it via curl or even with nodered, there is a problem retrieving the device list.

### Expected Behavior

get devices list

### Steps To Reproduce

use nodered contrib node-red-contrib-switchbot-api version 0.1.4 or use curl command

`curl -X GET https://api.switch-bot.com/v1.0/devices -H "Authorization: <your-api-token>" -H "Content-Type: application/json; charset=utf8"`

### Logs

```markdown
I get this error message

{"statusCode":190,"body":{},"message":"Cannot read properties of undefined (reading 'device_type')"}
```

### Configuration

```json
Nodered, curl
```

### Environment

- OS: Raspian
- Software: nodered
- Node: v16.20.2
- npm: 8.19.4

**Comment by donavanbecker** [comment]
What devices do you have?

**Comment by corasaniti** [comment]
@donavanbecker 
I only noticed it today because I updated Nodered to the latest version, and when the Docker container starts it tries to recover theSwitch bot devices list. This failed today, but perhaps the problem had existed for many days.
Thanks again

**Comment by corasaniti** [comment]
@donavanbecker @SwitchBot 
The API 1.1 version 1.0 no longer supports OAUTH1 authentication which is instead required by this nodered contrib

[https://flows.nodered.org/node/node-red-contrib-switchbot-api](url)

For this reason I migrated to version 1.1 of the API using Python scripts that call the API via requests.
Thank You
