### ISSUE TITLE
After pairing smart lock pro on another phone, why do I still see the device in the pairing menu?

### ISSUE THREAD

**Issue by lenovomen** [OpenWonderLabs/SwitchBotAPI#314]
### Current Situation

I associated the switchbot smart lock pro lock with my iPhone 15. When I'm near the lock with another phone in the switchbot app I can still see the lock in the pairing menu, but I can't pair it because the blue led isn't flashing and it's already paired with my iphone. Is it normal for it to appear? 

### Logs

```markdown
I don't have logs
```

### Configuration

```json
I don't have configuration
```

### Environment

- OS: IOS 17.5.1
- Software: switchbot 8.5
- Node: none
- npm: none

**Comment by lenovomen** [comment]
![IMG_0497](https://github.com/OpenWonderLabs/SwitchBotAPI/assets/110792755/3d2238b5-0e60-43e5-b4fe-c031b9a4b021)

Here is a picture of the problem.

**Comment by donavanbecker** [comment]
This has nothing to do with the API. Closing.
