### ISSUE TITLE
Curtain 2 not recognized in Home Assistant

### ISSUE THREAD

**Issue by EAuckland** [OpenWonderLabs/SwitchBotAPI#318]
### Analysis

I have 2 curtain 1 devices, 6 curtain 3 devices, 4 blind devices, a hub 1 and hub 2, and 2 curtain 2 devices. All show up and work great in Home Assistant except for the 2 Curtain 2's. I am running the updated firmware 4.6 on the curtain 2's however still nothing in Home Assistant.

### Expected Behavior

I expect to have the curtain 2's recognized as new devices just like all the other switchbot devices.

### Steps To Reproduce

Look in switchbot integration.

### Logs

```markdown
There is no log since there is no recognition.
```

### Configuration

```json
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#Ryobi
light:
  - platform: ryobi_gdo3
    username: !secret ryobi_username
    password: !secret ryobi_password
    device_id:
      - !secret ryobi_device_id
cover:
  - platform: ryobi_gdo3
    username: !secret ryobi_username
    password: !secret ryobi_password
    device_id:
      - !secret ryobi_device_id
      
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
```

### Environment

- OS: HAOS 12.4
- Software: SwitchBot Bluetooth
- Node: N/A
- npm: N/A

**Comment by donavanbecker** [comment]
Open issue with HA.
