### ISSUE TITLE
Getting Status via Switchbot API causes activation of motor for Switchbot Curtain

### ISSUE THREAD

**Issue by koshisan** [OpenWonderLabs/SwitchBotAPI#32]
**Describe The Bug:**

When I am requesting the status of a Switchbot Curtain it sometimes causes the device to move. The motor is only running very shortly - maybe for half a second or so, but it is clearly audible.

**To Reproduce:**

Sending a request to the /status URL causes this behaviour sometimes. When trying to close an already closed curtain through Alexa the same short movement is triggered.

**Expected behavior:**

The expectation would be that accessing /status only gives the last known status of the device. Either without accessing the device at all (if the position is stored in the cloud) or directly from the device - under no circumstances should the motor be triggered.

**Screenshots:**

NA

**Device Model:**

Switchbot Curtain

# **SwitchBotAPI**

- **Use Case**:
NA

**Comment by koshisan** [comment]
Is this project still being maintained?

**Comment by koshisan** [comment]
Update: The problem was with my setup. The question about active maintanance, however, remains...

**Comment by Minsheng** [comment]
> Update: The problem was with my setup. The question about active maintanance, however, remains...

Hello koshisan, 
This is Davidson from the dev team. Sorry for the late reply! We will continue to maintain this project but we are really busy working on the app improvement and the new products. I cannot promise to fix the API issues right away but I will talk to the team to look into the issues late June. Again, we do want to keep this community active. Thanks a lot for your attention and participation!

Cheers,
Davidson
