### ISSUE TITLE
Getting status of an infrared remote

### ISSUE THREAD

**Issue by YutaroEnomoto** [OpenWonderLabs/SwitchBotAPI#37]
**Is your feature request related to a problem? Please describe.**
It seems that the status of an infrared remote cannot be obtained through this API even though the similar can be done for other devices like a SwitchBot curtain. 
At least, I could not find out how to do this by reading README.
For example, I want to get the current settings of my air conditioner, such as temperature and mode.
I think we should be able to do this through the API since the same thing can be done in the smartphone app.

**Describe the solution you'd like**
If something like
GET https://api.switch-bot.com/v1.0/devices/{infraredRemoteId}/status
returned the status of the infrared remote, it would be very nice.

**Describe alternatives you've considered**

**Additional context**

**Comment by johnuopini** [comment]
This is still an issue, the app has thermostat status but this can't be seen from  the API

**Comment by ric-101** [comment]
Please reopen

**Comment by nenemo** [comment]
This is still an issue, the app has AC status but this can't be seen from the API. Please fix!
