### ISSUE TITLE
get Temperature and humidity, will be 0, but it will be statusCode":100.

### ISSUE THREAD

**Issue by taikoyourouyo** [OpenWonderLabs/SwitchBotAPI#371]
### Current Situation

with C# code, refer to sample code
request2 = new HttpRequestMessage(HttpMethod.Get, @"https://api.switch-bot.com/v1.1/devices/CA5FC0C6735E/status");

I was able to check the temperature and humidity using the smartphone app.

### Logs

```markdown
{"statusCode":100,"body":{"version":"V3.1","temperature":0,"battery":0,"humidity":0,"deviceId":"CA5FC0C6735E","deviceType":"Meter","hubDeviceId":"000000000000"},"message":"success"}
```

### Configuration

```json
using System;
using System.Diagnostics;
using System.Text;
using System.Security.Cryptography;
using System.Net.Http;

//トークンキーとシークレットキー
string token = "";
string secret = "";
DateTime dt1970 = new DateTime(1970, 1, 1);
DateTime current = DateTime.Now;
TimeSpan span = current - dt1970;
long time = Convert.ToInt64(span.TotalMilliseconds);
string nonce = Guid.NewGuid().ToString();
string data = token + time.ToString() + nonce;
Encoding utf8 = Encoding.UTF8;
HMACSHA256 hmac = new HMACSHA256(utf8.GetBytes(secret));
string signature = Convert.ToBase64String(hmac.ComputeHash(utf8.GetBytes(data)));

HttpClient client2 = new HttpClient();
var request2 = new HttpRequestMessage(HttpMethod.Get, @"https://api.switch-bot.com/v1.1/devices/CA5FC0C6735E/status");
request2.Headers.TryAddWithoutValidation(@"Authorization", token);
request2.Headers.TryAddWithoutValidation(@"sign", signature);
request2.Headers.TryAddWithoutValidation(@"nonce", nonce);
request2.Headers.TryAddWithoutValidation(@"t", time.ToString());
var response2 = await client2.SendAsync(request2);
Console.WriteLine(await response2.Content.ReadAsStringAsync());
```

### Environment

- OS: Windows11
- Software: VisualStudio
- Code: C#

**Comment by taikoyourouyo** [comment]
When I asked if it was an initial defect, I was directed here. nice to meet you

**Comment by hsakoh** [comment]
The fact that the hubDeviceId is set to "000..." suggests that the Meter is not connected to the internet. While the app and the Meter device exchange data via Bluetooth, a hub is required to send data to the SwitchBot cloud service and retrieve it via the API.

**Comment by taikoyourouyo** [comment]
That's what you meant. thank you.

>a hub is required to send data to the SwitchBot cloud service
Is this means switch-bot-hub? Or can I use Google nest hub?

I am reading this page.
https://support.switch-bot.com/hc/ja/articles/360037747514-%E3%83%9C%E3%83%83%E3%83%88%E3%81%A8Google-Home%E3%81%AE%E9%80%A3%E6%90%BA%E6%96%B9%E6%B3%95

**Comment by hsakoh** [comment]
You will need one of the following: SwitchBot Hub Mini, Hub 2, Ceiling Light, or Ceiling Light Pro.

**Comment by taikoyourouyo** [comment]
I understand. thank you

**Comment by taikoyourouyo** [comment]
Sorry, close.
