### ISSUE TITLE
Can't resolve API DNS

### ISSUE THREAD

**Issue by baty0man** [OpenWonderLabs/SwitchBotAPI#378]
### Current Situation

The API DNS (https://api.switch-bot.com/) is not resolving

### Logs

```markdown
Traceback (most recent call last):
  File "C:\Users\yohan\OneDrive\Desktop\switchbot-click.py", line 60, in <module>
    response = toggle_switchbot(payload_switchbot_turn_off)
  File "C:\Users\yohan\OneDrive\Desktop\switchbot-click.py", line 18, in toggle_switchbot
    response_post_switchbot = requests.request("POST", url_switchbot, headers=headers_switchbot, data=state).json()
                              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yohan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\yohan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\yohan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.switch-bot.com', port=443): Max retries exceeded with url: /v1.0/devices/-/commands (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024726666CF0>: Failed to resolve 'api.switch-bot.com' ([Errno 11001] getaddrinfo failed)"))
```

### Configuration

```json
def toggle_switchbot(state):
  response_post_switchbot = requests.request("POST", url_switchbot, headers=headers_switchbot, data=state).json()
  if response_post_switchbot['message'] == "success":
    return True
  else:
    return False

payload_switchbot_turn_on = "{\"command\":\"turnOff\"}"
payload_switchbot_turn_off = "{\"command\":\"turnOff\"}"
payload_input_boolean_turn_on = json.dumps({
  "state": "on"
})
payload_input_boolean_turn_off = json.dumps({
  "state": "off"
})

url_switchbot = "https://api.switch-bot.com/v1.0/devices/{device_id}/commands"
```

### Environment

- OS: Windows
- Software: Python 3.13.1
- Node:
- npm:

### Additional Context

- It was working before
- It stopped working after this issue: https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374
- I am based in Australia

**Comment by dirbz** [comment]
Based in AU as well. Both HA and this repo have closed their Issues, but it is not resolved for those of us in Australia.

**Comment by markjustmark** [comment]
So, api.switch-bot.com is a CNAME record that points to api.switchbot.net
api.switchbot.net is a CNAME record that points to the local regional servers that actually host the API service.

When you query a US DNS server (129.250.35.250), you get this:
```
nslookup api.switchbot.net 129.250.35.250 
Server:  x.ns.gin.ntt.net
Address:  129.250.35.250

Non-authoritative answer:
Name:    d-99k5evl0bf.execute-api.us-east-1.amazonaws.com
Addresses:  50.19.146.81
          3.234.78.251
          54.198.113.220
Aliases:  api.switchbot.net
```

When you query an EU DNS server (194.168.4.123), you get this
```
nslookup api.switchbot.net 194.168.4.123
Server:  buscache1.service.virginmedia.net
Address:  194.168.4.123

Non-authoritative answer:
Name:    d-05yzqxvv47.execute-api.eu-central-1.amazonaws.com
Addresses:  3.72.199.232
          52.29.109.238
Aliases:  api.switchbot.net
```
When you query a Singapore DNS server (203.126.238.211), you get this
```
nslookup api.switchbot.net 203.126.238.211 
Server:  UnKnown
Address:  203.126.238.211

Non-authoritative answer:
Name:    d-isgqcucw72.execute-api.ap-northeast-1.amazonaws.com
Addresses:  52.196.215.4
          43.206.196.170
          52.192.133.221
Aliases:  api.switchbot.net
```
Note that each region resolves to different servers in AWS

Now, when you try it on an Australian DNS server (61.8.0.113)
```
nslookup api.switchbot.net 61.8.0.113
Server:  UnKnown
Address:  61.8.0.113

Name:    api.switchbot.net
```

The Australian regional DNS geo-locating CNAME thingy is missing from all AU DNS servers that I can find (including 1.1.1.1 and 8.8.8.8, when checked from AU)

**Comment by Chrisj76au** [comment]
I have the same issue even tried the HACS SwitchBot Remote IR for Home Assistant which updated this morning with a new API address and that does not work either.

**Comment by sloaiza86** [comment]
I have the same issue in Latin America (Paraguay)

**Comment by markjustmark** [comment]
As a temporary workaround, I've put
```
	35.153.247.197	api.switchbot.net	api.switch-bot.com
```
in the etc/hosts (or C:\windows\system32\drivers\etc\hosts) on the box that runs the API queries

Note that you will have to remove this line when they fix the AU DNS CNAME

**Comment by markjustmark** [comment]
![image](https://github.com/user-attachments/assets/622434a6-407f-42bd-a0f1-37026b72d87e)

**Comment by markjustmark** [comment]
So now, how do we tell people at Switchbot that their geo-balancing CNAME DNS records are missing from Australian DNS servers?
(I tried going through their help chat bot last night and failed to get anyone to take notice)

**Comment by sloaiza86** [comment]
> So now, how do we tell people at Switchbot that their geo-balancing CNAME DNS records are missing from Australian DNS servers? (I tried going through their help chat bot last night and failed to get anyone to take notice)

And LATAM :')

**Comment by markjustmark** [comment]
Hopefully when they see it's broken in one place, they will check all the other places as well.

**Comment by Chrisj76au** [comment]
> Hopefully when they see it's broken in one place, they will check all the other places as well.

Hopefully they fix it soon I tried your work around but I'm running HA OS on a proxmox vm so I tried to add the dns into PI-Hole got a different error but still no luck .

**Comment by sloaiza86** [comment]
> > Hopefully when they see it's broken in one place, they will check all the other places as well.
> 
> Hopefully they fix it soon I tried your work around but I'm running HA OS on a proxmox vm so I tried to add the dns into PI-Hole got a different error but still no luck .

I was trying something similar, but then I changed the DNS of HA OS to 129.250.35.250 (thanks to @markjustmark for the different DNSs lists) and now is working... That will increase the resolution time so should be rolled back when solved.

**Comment by Chrisj76au** [comment]
> 194.168.4.123

Thanks I gave it a try but still no luck tried a few different DNS kept getting

 raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host api.switch-bot.com:443 ssl:default [DNS server returned answer with no data]

**Comment by markjustmark** [comment]
> > 194.168.4.123
> 
> Thanks I gave it a try but still no luck tried a few different DNS kept getting
> 
> raise ClientConnectorDNSError(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host api.switch-bot.com:443 ssl:default [DNS server returned answer with no data]

I just picked some from https://public-dns.info/#countries

**Comment by sloaiza86** [comment]
Did you try a full reboot of the HA OS in order to flush the DNS table? And just to be sure, are you configuring only one of the DNS of markjusrmark post that resolve ok and deleting all other DNS from the network settings?

 
![image](https://github.com/user-attachments/assets/ca8a7c79-fc5b-49c7-9eb4-cb60b9073608)
