### ISSUE TITLE
SwitchBot Motion Sensor & Contact Sensor API support

### ISSUE THREAD

**Issue by ajitesh1828** [OpenWonderLabs/SwitchBotAPI#40]
Please enable support for Motion Sensor and Contact sensor (Camera as well). Currently API return success without any attributes/information.

Thank you!

**Comment by elzup** [comment]
I wont the most getting history logs feature.
I'm waiting

**Comment by TristanBrotherton** [comment]
Another vote for this!

**Comment by yjeanrenaud** [comment]
true. this is needed badly

**Comment by huzisuke** [comment]
Is there another API?
I can't get these sensor status with "GET /v1.0/devices/{deviceId}/status" method.

Please additional API information.

**Comment by SwitchBot-Wonderlabs** [comment]
It has been updated, please check the latest API documentation.
Thank you.

**Comment by donavanbecker** [comment]
Thanks! This has been implemented into the latest version of @switchbot/homebridge-switchbot

**Comment by yjeanrenaud** [comment]
great news. Now we just need it at homebridge-switchbot-openapi, too

**Comment by donavanbecker** [comment]
> great news. Now we just need it at homebridge-switchbot-openapi, too

@yjeanrenaud I will be decommissioning that plugin to combine the two plugins to support both BLE and OpenAPI
