### ISSUE TITLE
Temperature/humidity sensor recognised as sensor within HomeKit

### ISSUE THREAD

**Issue by hectorkd** [OpenWonderLabs/SwitchBotAPI#43]
**Is your feature request related to a problem? Please describe.**

Somewhat. The SwitchBot temperature and humidity sensor don't get recognised as a sensor within HomeKit.

**Describe the solution you'd like**

The SwitchBot temperature and humidity sensor to be recognised as a sensor within HomeKit

**Describe alternatives you've considered**

I don't think there are any alternatives.

**Additional context**

If it could be recognised as a sensor within HomeKit, you could be opened up to creating HomeKit automations that occur when a temperature/humidity is reached.

**Comment by donavanbecker** [comment]
@hectorkd are you using a homebridge or your on HomeKit project?

**Comment by hectorkd** [comment]
I am using HOOBS

**Comment by donavanbecker** [comment]
This is the api repo, Not a plugin for homebridge.
