### ISSUE TITLE
Brightness field is used in different ways

### ISSUE THREAD

**Issue by alamers** [OpenWonderLabs/SwitchBotAPI#48]
**Describe The Bug:**
The documentation for the `GET /v1.0/devices/{deviceId}/status` mentions the field `brightness` twice, with different definitions. It looks like the motion sensor and contact sensor report a different type than the color bulb.

**To Reproduce:**

See [documentation](https://github.com/OpenWonderLabs/SwitchBotAPI#responses-1)

**Expected behavior:**

Probably one of the brightness fields should be called differently. The way it is described now makes it very hard to integrate with this API from strongly typed languages such as Java (I am working on an OpenHAB implementation), as there are two types defined for the same field name.

**Device Model:**
Motion sensor/Contact sensor/Light bulb.

**Comment by yjeanrenaud** [comment]
well spotted!

**Comment by nasa9084** [comment]
not close

**Comment by waku1123** [comment]
Im also having trouble with the same problem while developing in golang...

**Comment by nasa9084** [comment]
@waku1123 btw, I wrote switchbot client for golang, which supports current brightness issue, use this if you want: https://github.com/nasa9084/go-switchbot

**Comment by waku1123** [comment]
@nasa9084 cool!!! This is exactly what I am looking for!

**Comment by yjeanrenaud** [comment]
no updates here, though?
