### ISSUE TITLE
Token please?

### ISSUE THREAD

**Issue by strunker** [OpenWonderLabs/SwitchBotAPI#5]
I also sent a request in for token I used the option "ask a question" hopefully that gets routed correctly. Is there a more official way to request a token at this time? I will be writing my own rest code I do not use homebridge, or any other platform for that matter, at all. Thanks.

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @strunker , what's your SwitchBot account?

**Comment by jahnkenneth** [comment]
I have also sent a request, but not gotten a token. 
jahn.k.juliussen@me.com

**Comment by strunker** [comment]
@SwitchBot-Wonderlabs  my account would be fortestinglb@gmail.com 

for the record I wish that usernames != emails. Typically I wouldnt share my email publicly in this fashion. Its a better design to have obfuscation behind generic id names in my opin. 

Thanks.

**Comment by SwitchBot-Wonderlabs** [comment]
The latest version of the Android app can generate tokens!

**Comment by SwitchBot-Wonderlabs** [comment]
Android v5.0.0
The developer option is hidden by default. 
Please click App Version 10 times in Preference.

**Comment by strunker** [comment]
I only have version 4.9.7 and there isn't an option for me to upgrade last that for android. Thanks.
________________________________

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @strunker , I also sent you an email.

**Comment by strunker** [comment]
Got it so I just need to wait then for now? If it's gnna roll out soon I guess there isn't much need to issue a token outside of the app flown

**Comment by SwitchBot-Wonderlabs** [comment]
> Got it so I just need to wait then for now? If it's gnna roll out soon I guess there isn't much need to issue a token outside of the app flow

I have emailed token to you. You can try [homebridge-switchbot-openapi](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi).

**Comment by strunker** [comment]
I'm trying to just code against the raw protocol. I can do that with this token I would imagine as well yes? Also I have not received any of the emails you have sent sadly ;(
________________________________

**Comment by SwitchBot-Wonderlabs** [comment]
Please check the SwitchBot account email.
It's Gmail.
I sent it again.

**Comment by SwitchBot-Wonderlabs** [comment]
I received your reply.
You can develop based on this API documentation.
