### ISSUE TITLE
SwitchBot Meter: Add commands

### ISSUE THREAD

**Issue by raphael-leger** [OpenWonderLabs/SwitchBotAPI#51]
**Is your feature request related to a problem? Please describe.**

I would like to access the temperatures history of a SwitchBot Meter via the API.

Not just the current temperature but the past history.

**Describe the solution you'd like**

There could be a command for the Meter called `getTemperatureHistory` that returns all the temperatures values collected by the device.

It could be the exact same CSV that we have when we click "export data" in SwitchBot app or it could be some json like so:

```json
{
    "temperatures": [
       { "date": "2021-08-08 09.18", "value": 24.5 },
       { "date": "2021-08-08 09.23", "value": 24.2 },
       { "date": "2021-08-08 09.38", "value": 23.5 }
    ]
}
```

**Describe alternatives you've considered**
A dedicated endpoint?

**Additional context**
None

**Comment by elzup** [comment]
I also want it very much.
I'm now polling (device/state API) every 15 seconds. It's That is extremely inefficient.

I trying to detect that the sensor is not responding (Motion sensor) for 30 minutes in a row.
If exists history API smartly, I can change to a design that makes a reservation 30 minutes after the last detected time.
and, I can Tracking another sensor (my refrigerator's Contact Sensor) use API Limit Resources.
