### ISSUE TITLE
Simple way to get the API key

### ISSUE THREAD

**Issue by AdyRock** [OpenWonderLabs/SwitchBotAPI#54]
**Is your feature request related to a problem? Please describe.**

For many users, getting the API key from the app is awkward plus they have to copy that to the other automaton system which often leads to mistakes and frustration.

**Describe the solution you'd like**

Add an API call that takes the username and password and returns the API key.

**Describe alternatives you've considered**

OAuth2 authentication but this requires a lot more complexity.

**Additional context**

The aim of most systems is simplicity. If a system is too complex / error prone then users will give up and seek other solutions.

**Comment by donavanbecker** [comment]
@AdyRock 

The API key can be retrieved from clicking the app version 10 times, then going to developer options. All under profile preferences.
