### ISSUE TITLE
Status of leaving home/entering home via Contact Sensor 

### ISSUE THREAD

**Issue by gyama11** [OpenWonderLabs/SwitchBotAPI#61]
**Is your feature request related to a problem? Please describe.**

‎The Contact Sensor named W1201500 cannot get "leaving home/entering home" mode via API.
If I got information above, I could buy materials. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AdyRock** [comment]
I would also like to see that information in the cloud API.

**Describe the solution you'd like**
add the fields to the status object:
`homeCount: x,`
`awayCount: x,`

Where x is incremented each time a leaving home or entering home event occurs.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
By using a count we can see if the event has occurred sine the last call to get the status.

**Comment by AdyRock** [comment]
Will this be added?

**Comment by AdyRock** [comment]
Any news about this?

**Comment by AdyRock** [comment]
Any progress yet?

**Comment by AdyRock** [comment]
Any progress?

**Comment by gyama11** [comment]
Mr. AdyRock
I am very sorry to reply your answer.
Yes, add the fields to the status object with increment number.

This BlackFriday, I get the sensor W1201500. I want the status object feature...
Regards
gyama

**Comment by AdyRock** [comment]
Any reason you have closed the issue before SwitchBot have taken any action?

**Comment by gyama11** [comment]
Mr. AdyRock
Your mention that "homeCount" or "awayCount" cannot be obtained via the cloud API. Only status of open/closed can obtained. Nevertheless W1201500 has physical button. The status of "Go Out" or "In Home" that I want.
I understand current specification of the cloud API, I cannot solve anymore so closed the issue. thanks.

**Comment by AdyRock** [comment]
Just to be clear, I was agreeing with you and supporting your request for the feature. I don't work for SwitchBot and I was not telling you it would not be possible.
I think your request is a good idea and I would also like to see it implemented.
Best regards,
Adrian.
