### ISSUE TITLE
Custom IR device wont work 

### ISSUE THREAD

**Issue by 1liminal1** [OpenWonderLabs/SwitchBotAPI#65]
I can get a list of devices doing:

curl -H "Authorization:xxxxxxxxxxxxxxxxxxxx" https://api.switch-bot.com/v1.0/devices

I see the device in the list of devices

"infraredRemoteList":[{"deviceId":"xxxxxxxxxxxxxxxxxxxxxx","deviceName":"Bedroom Fan","remoteType":"Others","hubDeviceId":"xxxxxxxxxxxxxxxx"}]}

But If I try to get the status:

curl -H "Authorization:xxxxxxxxxxxxxxxxxxxxxxxx" https://api.switch-bot.com/v1.0/devices/xxxxxxxxxxxxxxxxxxx/status

I get the following error:

{"statusCode":190,"body":{},"message":"wrong deviceId"}

Also I have added this as a switch into Home Assistant. I have three switchbot and two curtains. all works fine.

But cant get the fan to do anything

my code

  - platform: template
    switches:
      aircon_switch:
        friendly_name: "Bedroom Fan"
        unique_id: bedroom_fan_switch
        turn_on:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_fan_deviceId
            command: "turnOn"
        turn_off:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_fan_deviceId
            command: "turnOff"
Please advise?

Thanks so much :)

I can get a list of devices doing:

curl -H "Authorization:xxxxxxxxxxxxxxxxxxxx" https://api.switch-bot.com/v1.0/devices

I see the device in the list of devices

"infraredRemoteList":[{"deviceId":"xxxxxxxxxxxxxxxxxxxxxx","deviceName":"Bedroom Fan","remoteType":"Others","hubDeviceId":"xxxxxxxxxxxxxxxx"}]}

But If I try to get the status:

curl -H "Authorization:xxxxxxxxxxxxxxxxxxxxxxxx" https://api.switch-bot.com/v1.0/devices/xxxxxxxxxxxxxxxxxxx/status

I get the following error:

{"statusCode":190,"body":{},"message":"wrong deviceId"}

Should turn on the fan

Im not posting for security 

**Device Model:**

Custom IR device (fan) added to hub

# **SwitchBotAPI**

- **Use Case**:

Using HA to turn on and off bedroom fan

**Comment by 1liminal1** [comment]
Anyone?

**Comment by QuixThe2nd** [comment]
Im facing the same issue

**Comment by AdyRock** [comment]
It is not possible to get the status of remote devices as they are send only devices.
The API document says this:

```
Get the status of a physical device that has been added to the current user's account.

Physical devices refer to the following SwitchBot products,

Bot
Plug
Curtain
Meter
Motion Sensor
Contact Sensor
Color Bulb
Humidifier
Smart Fan
```

**Comment by 1liminal1** [comment]
Ok that does make sense. I did manage to get in working. Custom button commands are whatever you name them. ie On and not TurnOn

**Comment by QuixThe2nd** [comment]
@1liminal1 You could always use IFTTT, that's what I ended up using.
