### ISSUE TITLE
Hello! i need help with the switchbot api

### ISSUE THREAD

**Issue by Toxic-Omega** [OpenWonderLabs/SwitchBotAPI#73]
i have been recently developing a switchbot app for windows that uses the api,
and i have been trying to figure out what are the name of buttons that are circled in red
i have tried : arrow_Up, Up, upArrow but none of them work,
i read https://github.com/OpenWonderLabs/SwitchBotAPI#command-set-for-virtual-infrared-remote-devices , but i have not found anything about the name of these button!
Can you guys please help me!?

Image : https://ibb.co/cNnJ4hR

**Comment by Toxic-Omega** [comment]
can somebody please help?

**Comment by Pierre-Cerou** [comment]
Hello, I'm facing the same issue about unknown codes for some buttons. For a DVD IR Remote, commands like Eject or pop-up menu, home, and so on ...

Is there a way to get the full list of commands ?
