### ISSUE TITLE
Home Assistant Integration is not working: "no unconfigured devices found"

### ISSUE THREAD

**Issue by areinhar87** [OpenWonderLabs/SwitchBotAPI#74]
**HA integration stops: "no unconfigured devices found" 
I try to integrate contact sensors and motion sensors. how can i fix th bug?
<img width="1435" alt="Bildschirmfoto 2021-12-22 um 10 14 16" src="https://user-images.githubusercontent.com/94788039/147072925-09fd2ebe-683b-456b-8cf9-81c52487e2f1.png">
**

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Device Model:**

# **SwitchBotAPI**

- **Use Case**:

**Comment by bradasteiner** [comment]
Having the same issue. I have a switch bot connected to a switch bot hub

**Comment by donavanbecker** [comment]
Home Assistant uses BLE, so not relevant to this repo try: pySwitchBot.
