### ISSUE TITLE
Status of leaving home/entering home via Contact Sensor

### ISSUE THREAD

**Issue by AdyRock** [OpenWonderLabs/SwitchBotAPI#75]
**Is your feature request related to a problem? Please describe.**
The Contact Sensor we cannot get "leaving home/entering home" mode via API.

**Describe the solution you'd like**
add the fields to the status object:
homeCount: x,
awayCount: x,

Where x is incremented each time a leaving home or entering home event occurs.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
By using a count we can see if the event has occurred sine the last call to get the status.

**Comment by chenliuyun** [comment]
Hi, the webhook should solve it, I will close this issue, If you have any other questions, please feel free to feedback. Thanks
