### ISSUE TITLE
HOOBS: Warning plugin site unavailable

### ISSUE THREAD

**Issue by PBXLthrMan** [OpenWonderLabs/SwitchBotAPI#76]
**Describe The Bug:**

I'm trying to install the certified HOOBS Plugin SwitchBot and I keep getting Warning plugin site unavailable and the plugin installation fails.

**To Reproduce:**

1. Launch HOOBS.
2. Go into Plugins
3. Search for SwitchBot
4. Click SwitchBot (Certified)
5. Click install

**Expected behavior:**

A successful installation.

**Screenshots:**

12/26/2021, 11:23:13 PMSwitchbot Bridge starting
12/26/2021, 11:23:36 PMWARNINGplugin site unavailable
12/26/2021, 11:23:39 PMSwitchbot BridgeWARNINGNo plugins installed.
12/26/2021, 11:23:40 PMSwitchbot BridgeBridge is running on port 51866.
12/26/2021, 11:24:46 PMAlexa BridgeAlexaERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.
12/26/2021, 11:27:54 PMWARNINGplugin site unavailable
12/26/2021, 11:27:54 PMWARNINGplugin site unavailable
12/26/2021, 11:27:54 PMWARNINGplugin site unavailable
12/26/2021, 11:31:50 PMWARNINGplugin site unavailable
12/26/2021, 11:31:50 PMWARNINGplugin site unavailable
12/26/2021, 11:31:50 PMWARNINGplugin site unavailable
12/26/2021, 11:31:51 PMAlexa BridgeAlexaERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

Then goes to: "Unable to install plugin. Please try again."

**Device Model:**

HOOBS 4.x

# **SwitchBotAPI**

- **Use Case**:

**Comment by donavanbecker** [comment]
@PBXLthrMan This has nothing to do with the api, it would be with the homebridge plugin.
