### ISSUE TITLE
API using JS

### ISSUE THREAD

**Issue by galepsh** [OpenWonderLabs/SwitchBotAPI#81]
**Describe The Bug:**

I can't maks JS calls to the API due to CORS policy.

**To Reproduce:**

I try to access my devices using JS fetch request:

fetch('https://api.switch-bot.com/v1.0/devices', {
method: 'GET',
headers: {
"ContentType": "application/json; charset=utf8",
'Authorization': myToken,
},
}).then(r => console.log(r)).catch(err => console.log(err));

but I keep getting the error:
Access to fetch at 'https://api.switch-bot.com/v1.0/devices' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any way to solve it?

**Expected behavior:**

Make the API work with JS

**Screenshots:**

**Device Model:**

macbook pro intel i5

# **SwitchBotAPI**

- **Use Case**:
use the API on Angular web app

**Comment by donavanbecker** [comment]
[Line 34](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/a276245d9ce7c01741a354f7273425d38c9f5acb/src/platform.ts#L34)
[Line 70](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/a276245d9ce7c01741a354f7273425d38c9f5acb/src/platform.ts#L70)
[Line 214](https://github.com/OpenWonderLabs/homebridge-switchbot/blob/a276245d9ce7c01741a354f7273425d38c9f5acb/src/platform.ts#L214)

here are examples where this is use in typescript. worth a look.

**Comment by NorihitoN** [comment]
> **Describe The Bug:**
> 
> I can't maks JS calls to the API due to CORS policy.
> 
> **To Reproduce:**
> 
> I try to access my devices using JS fetch request:
> 
> fetch('https://api.switch-bot.com/v1.0/devices', { method: 'GET', headers: { "ContentType": "application/json; charset=utf8", 'Authorization': myToken, }, }).then(r => console.log(r)).catch(err => console.log(err));
> 
> but I keep getting the error: Access to fetch at 'https://api.switch-bot.com/v1.0/devices' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> Any way to solve it?
> 
> **Expected behavior:**
> 
> Make the API work with JS
> 
> **Screenshots:**
> 
> **Device Model:**
> 
> macbook pro intel i5
> 
> # **SwitchBotAPI**
> * **Use Case**:
>   use the API on Angular web app

I have the same error.
