### ISSUE TITLE
Unable to obtain SwitchBot Lock status.

### ISSUE THREAD

**Issue by Mr-Argentum** [OpenWonderLabs/SwitchBotAPI#89]
**Describe The Bug:**
Unable to obtain SwitchBot Lock status.

**To Reproduce:**
I tried to get the state of SwitchBot Lock, but the Body part returns empty.

**Expected behavior:**
`curl -X GET -H "Authorization: xxx" https://api.switch-bot.com/v1.0/devices/ABCD1234/status

{"statusCode":100,"body":{},"message":"success"}`

**Screenshots:**

**Device Model:**

# **SwitchBotAPI**

- **Use Case**:

**Comment by yonutz33** [comment]
But i am having the exact same problem!!!

**Comment by yhirochick** [comment]
Me too.

**Comment by yhirochick** [comment]
@Mr-Argentum @yonutz33 
I figured out.
I was setting "hubDeviceId" not "deviceId".
In my case, It's "Thermometer and Hygrometer(Meter)" .
When I set "hubDeviceId", the response body is empty, But When I set "deviceId", the response includes  the status of Meter.
